### PR TITLE
Export /proc/self-thread and /proc/[pid]/task

### PR DESCRIPTION
**Pull request by grief8**
This pull request introduces several updates and new features to the `procfs` module in the kernel. The most significant changes include the addition of support for the `thread-self` symbolic link and the `/proc/[pid]/task` directory, along with the necessary restructuring of imports and modules.

### New Features:
* Added support for the `thread-self` symbolic link, which points to the current thread's directory. (`kernel/src/fs/procfs/thread_self.rs`)
* Introduced the `/proc/[pid]/task` directory to represent the tasks (threads) of a process. (`kernel/src/fs/procfs/pid/task.rs`)

### Code Restructuring:
* Moved and restructured imports for better organization and clarity in `kernel/src/fs/procfs/mod.rs`. [[1]](diffhunk://#diff-ef4c7ad7803b981b000b99038edcee86cd4252c92cc34f15f0783bf09cd05865L5-R13) [[2]](diffhunk://#diff-ef4c7ad7803b981b000b99038edcee86cd4252c92cc34f15f0783bf09cd05865L22-R25)
* Added the `thread_self` module to the `procfs` directory. (`kernel/src/fs/procfs/mod.rs`)

### Directory Operations:
* Updated `RootDirOps` to handle the `thread-self` symbolic link. (`kernel/src/fs/procfs/mod.rs`) [[1]](diffhunk://#diff-ef4c7ad7803b981b000b99038edcee86cd4252c92cc34f15f0783bf09cd05865R113-R114) [[2]](diffhunk://#diff-ef4c7ad7803b981b000b99038edcee86cd4252c92cc34f15f0783bf09cd05865R140-R142)
* Updated `PidDirOps` to include the `task` directory. (`kernel/src/fs/procfs/pid/mod.rs`) [[1]](diffhunk://#diff-da4386c37c4bc3afd221af9a3fe3ab4db54e9425c34086316c39f722090cac85R61) [[2]](diffhunk://#diff-da4386c37c4bc3afd221af9a3fe3ab4db54e9425c34086316c39f722090cac85R91-R93)

These changes enhance the functionality of the `procfs` module by providing better support for thread-specific information and improving the organization of process-related directories.

### CODE REVIEW

**Comment by grief8** [comment]
@boterinas ready

**Review by tatetian — COMMENTED** [review]
Are there any gvisor tests that cover these procfs inodes?

Rebase to the latest main branch to fix the probably random CI failures caused by bugs already fixed on the latest main branch.

**Comment by tatetian** [comment]
@boterinas author

**Comment by grief8** [comment]
> Are there any gvisor tests that cover these procfs inodes?
> 
> Rebase to the latest main branch to fix the probably random CI failures caused by bugs already fixed on the latest main branch.

Of course! I have added `proc_test` for procfs in the latest changes.

**Comment by grief8** [comment]
@boterinas ready

**Comment by grief8** [comment]
@boterinas rerun

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
