### PR TITLE
Use slab allocator to allocate heap

### PR DESCRIPTION
**Pull request by sdww0**

### CODE REVIEW

**Comment by tatetian** [comment]
How is the performance of the slab allocator crate compared to the original buddy system allocator?

**Comment by tatetian** [comment]
@Tangzh33 What is your opinion about adopting the slab allocator crate directly?

**Comment by sdww0** [comment]
> How is the performance of the slab allocator crate compared to the original buddy system allocator?

I only tested the `lat_sem`. After using the slab allocator crate, the result of `lat_sem` has improved from 0.4746 us to 0.4630 us.

**Comment by Tangzh33** [comment]
Generally, it is a good attempt to retain the performance bottleneck caused by heap of `buddy_system_allocator`. I have carefully inspected the imported slab’s source code, and here are my findings.

The newly introduced slab comprises seven interconnected linked lists, in addition to a single Buddy Allocator. Each linked list represents a range of slab sizes, extending from 64 bytes to 4096 bytes. Concurrently, the Buddy Allocator is tasked with the management of objects exceeding the size of 4096 bytes.

The new slab allocation system surpasses the previous buddy system heap in terms of efficiency due to the following reasons:

1. The slab list serves as a pre-allocated cache for objects of corresponding sizes. Under most circumstances, the new heap can allocate objects with O(1) time complexity. This enhancement is inherently achieved through the integration of the slab allocation mechanism.
2. @sdww0 has meticulously implemented a new slab allocation system, thereby enabling the contemporary heap to effectively utilize pre-allocated memory segments, which are crucial for efficiency. The asynchronous preparation of these memory segments typically outperforms the allocation speed of dynamic data structures, such as vectors, in the majority of cases.

However, the new slab allocation system reveals certain disadvantages:

1. The linked list allocations commence at 64 bytes, which inevitably results in significant memory wastage during the allocation of small objects.
2. The new implementation fails to address the efficiency degradation stemming from the race conditions inherent in the Heap's SpinLock. I contend that the design of a heap with fine-granularity synchronization, or even a lock-free heap, should be the aspiration when crafting new heap.

In my opinion, this pull request has enhanced the performance of Asterinas's heap-related operations, yet it still presents areas that require further refinement.

**Comment by Tangzh33** [comment]
Generally, it is a good attempt to retain the performance bottleneck caused by heap of `buddy_system_allocator`. I have carefully read the imported slab’s source code, and the following are what I found.

The new slab is consisted of 7 linked list, as well as one BuddyAllocator. Each of linked list denotes that list of  slabs ranging from 64B to 4096B, while the buddy allocator is responsible for managing objects with size larger than 4096B.

New slab is better than previous buddy system heap at efficiency because: 

1. The slab list act as pre-allocated cache for corresponding objects. At most of the circumstances, new heap can allocate object at `O(1)` complexity, and this improvement is natually gained by importing slab.
2. @[[**sdww0](https://github.com/sdww0)](https://github.com/sdww0)** has transplant new slab well so that the new heap still use pre-allocated memory segment with rescue. Asynchronously prepared memory segment is faster than dynamic data structure like `vec` at most cases.

But the new slab exposes some drawbacks:

1. The linked list ranges begin with 64B, which will definitely waste a lot of memory while allocating small objects.
2. The new implementation does not solve the efficiency loss originated from the race condition of Heap’s SpinLock. I supposed that a heap with fine-granularity synchronization, or even a lock-free heap, should be the aspiration when designing new heap.

As far as I am concerned, this PR can boot up Asterinas heap-related efficiency, but still leaves many aspects to improve.

**Comment by sdww0** [comment]
@boterinas rerun

**Comment by sdww0** [comment]
@boterinas rerun

**Comment by tatetian** [comment]
Great. Then I think we can use the slab allocator crate directly in `ostd` and at the same time, start   figuring out a way to extract it out of `ostd` using the safe dependency injection technique.

**Comment by tatetian** [comment]
@sdww0 The PR looks good me. Any reason to keep it as a draft?

**Comment by sdww0** [comment]
> @sdww0 The PR looks good me. Any reason to keep it as a draft?

The CI `SMP Syscall Test (Multiboot2)` always failed in this PR. I tried to find out if this PR introduced it.

**Comment by sdww0** [comment]
@boterinas rerun

**Comment by junyang-zh** [comment]
This PR looks NOT good to me. Firstly let me clarify the two things that we need to do:

 1. Upgrade the global heap allocator with a better algorithm than the buddy system, for example, [tcmalloc](https://github.com/google/tcmalloc);
 2. Add a mechanism like `kmemcache` and introduce a slab implementation for the users; then make the users use the slab cache instead of the global heap when possible.

This PR tries to do 1. with a crate called `slab_allocator`. This PR does NOT address 2. It has nothing to do with the slab cache mechanism.

The `slab_allocator` crate also uses a slab-like mechanism for heap allocation. But is far from mature and tested. There's no full evidence of the performance advantage for adopting this crate, the `lat_sem` improvement seems too minor. And the memory wastage of this crate is substantial. I strongly discourage the use of the crate. To better address 1., we need just to implement tcmalloc or ptmalloc in Rust. As far as I am concerned there's no exsisting Rust implementation of any of the modern heap allocators.

**Comment by junyang-zh** [comment]
> > @sdww0 The PR looks good me. Any reason to keep it as a draft?
> 
> The CI `SMP Syscall Test (Multiboot2)` always failed in this PR. I tried to find out if this PR introduced it.

As for the SMP test, there's a known issue #1264 and a fix #1158

**Comment by sdww0** [comment]
> This PR looks NOT good to me. Firstly let me clarify the two things that we need to do:
> 
> 1. Upgrade the global heap allocator with a better algorithm than the buddy system, for example, [tcmalloc](https://github.com/google/tcmalloc);
> 2. Add a mechanism like `kmemcache` and introduce a slab implementation for the users; then make the users use the slab cache instead of the global heap when possible.
> 
> This PR tries to do 1. with a crate called `slab_allocator`. This PR does NOT address 2. It has nothing to do with the slab cache mechanism.
> 
> The `slab_allocator` crate just uses a slab-like mechanism for heap allocation. But it is far from mature and tested. There's no full evidence of the performance advantage for adopting this crate, the `lat_sem` improvement seems too minor. And the memory wastage of this crate is substantial. I strongly discourage the use of the crate. To better address 1., we need just to implement tcmalloc or ptmalloc in Rust. As far as I am concerned there's no exsisting Rust implementation of any of the modern heap allocators.
> 
> I've invited @azongchang to investigate the goal 1., and @Tangzh33 for the goal 2.

I also have no confidence in this crate which is the main reason why this PR is still in draft. I think this PR can be closed if we introduce a better algorithm for the global heap allocator soon (like 2/3 weeks).

**Comment by tatetian** [comment]
> The slab_allocator crate just uses a slab-like mechanism for heap allocation. But it is far from mature and tested.

Of course. I am not saying that the `slab_allocator` crate is perfect. I am just trying to figure out this question: is `slab_allocator` better than `buddy_system_allocator`?

This PR shows that adopting `slab_allocator` is quite easy. And if `slab_allocator` provides noticeable performance boost, then we should replace `buddy_system_allocator` with `slab_allocator`. This does not prevent us from pursuing the two goals that you mentioned, but it will take time to accomplish them.

@lucassong-mh Could you do me a favor by trying out this PR and see if it can boost the performance of Lmbench programs that involve frequent heap allocations such as the create-delete-files benchmark?

> The linked list ranges begin with 64B, which will definitely waste a lot of memory while allocating small objects.

This one should be easy to fix.

**Comment by lucassong-mh** [comment]
> @lucassong-mh Could you do me a favor by trying out this PR and see if it can boost the performance of Lmbench programs that involve frequent heap allocations such as the create-delete-files benchmark?

Results of mine:
cmd: `/benchmark/bin/lmbench/lat_fs -s 0k -P 1 -W 50 -N 500`

Without this PR (buddy):

| File size | Number of created then deleted | Created per second | Deleted per second |
| --------- | ------------------------------ | ------------------ | ------------------ |
| 0k        | 964                            | 178156             | 160843             |
| 1k        | 694                            | 133951             | 72953              |
| 4k        | 688                            | 123519             | 60477              |
| 10k       | 547                            | 102167             | 46329              |

Have this PR (slab):

| File size | Number of created then deleted | Created per second | Deleted per second |
| --------- | ------------------------------ | ------------------ | ------------------ |
| 0k        | 998                            | 183658             | 420988             |
| 1k        | 831                            | 153434             | 369561             |
| 4k        | 835                            | 152707             | 371044             |
| 10k       | 662                            | 128819             | 326284             |

I think using this slab allocator actually bring benefits to this benchmark, especially the file deletion performance (4th column) : ×2.6 ～ ×7.0. This seems to be consistent with the discussion in https://github.com/asterinas/asterinas/issues/1222.

While it seems the benefits on the 2nd and the 3rd column is not that outstanding and the creation becomes the bottleneck. I need to check the reason, and my https://github.com/asterinas/asterinas/pull/1262 can improve this from other aspects.

**Comment by sdww0** [comment]
Can I conclude that the PR is acceptable? After all, this PR only involves simple changes that will not impact our future implementation of modern heap allocators.

If this PR is acceptable, I will rebase and convert it to ready.

**Comment by tatetian** [comment]
> Can I conclude that the PR is acceptable? After all, this PR only involves simple changes that will not impact our future implementation of modern heap allocators.
> 
> If this PR is acceptable, I will rebase and convert it to ready.

Yes, I believe it is.

**Comment by tatetian** [comment]
@sdww0 Could you fix the Publish OSDK and OSTD check? 

```
error: all dependencies must have a version specified when publishing.
dependency `slab_allocator` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
```

**Comment by sdww0** [comment]
> @sdww0 Could you fix the Publish OSDK and OSTD check?
> 
> ```
> error: all dependencies must have a version specified when publishing.
> dependency `slab_allocator` does not specify a version
> Note: The published dependency will use the version from crates.io,
> the `git` specification will be removed from the dependency declaration.
> ```

I have fixed this problem, however it comes up with another issue. The procedure failed because of `linked_list_allocator-0.6.6` and `spin-0.4.10`. However, after checking the `slab_allocator` crate and its dependencies, I didn't find any usage of these crates. I will spend some time trying to fix it.

**Comment by tatetian** [comment]
> > @sdww0 Could you fix the Publish OSDK and OSTD check?
> > ```
> > error: all dependencies must have a version specified when publishing.
> > dependency `slab_allocator` does not specify a version
> > Note: The published dependency will use the version from crates.io,
> > the `git` specification will be removed from the dependency declaration.
> > ```
> 
> I have fixed this problem, however it comes up with another issue. The procedure failed because of `linked_list_allocator-0.6.6`. However, after checking the `slab_allocator` crate and its dependencies, I didn't find any usage of this crate. I will spend some time trying to fix it.

Maybe the `slab_allocator` crate is incompatible with our nightly Rust toolchain?

**Comment by sdww0** [comment]
> > > @sdww0 Could you fix the Publish OSDK and OSTD check?
> > > ```
> > > error: all dependencies must have a version specified when publishing.
> > > dependency `slab_allocator` does not specify a version
> > > Note: The published dependency will use the version from crates.io,
> > > the `git` specification will be removed from the dependency declaration.
> > > ```
> > 
> > 
> > I have fixed this problem, however it comes up with another issue. The procedure failed because of `linked_list_allocator-0.6.6`. However, after checking the `slab_allocator` crate and its dependencies, I didn't find any usage of this crate. I will spend some time trying to fix it.
> 
> Maybe the `slab_allocator` crate is incompatible with our nightly Rust toolchain?

Found the problem. The [Cargo book](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations) says: 

```toml
[dependencies]
# Uses `my-bitflags` when used locally, and uses
# version 1.0 from crates.io when published.
bitflags = { path = "my-bitflags", version = "1.0" }

# Uses the given git repo when used locally, and uses
# version 1.0 from crates.io when published.
smallvec = { git = "https://github.com/servo/rust-smallvec.git", version = "1.0" }
```

Since the `slab_allcator` from `acreos-org` is based on [`slab_allocator v0.3.1`](https://github.com/weclaw1/slab_allocator). The publish procedure use the v0.3.1 from the crates.io and cause this issue.

**Comment by tatetian** [comment]
> I think we can fork the [slab_allcator from acreos-org](https://github.com/arceos-org/slab_allocator) and bump the version to 0.4.0 or another version to avoid this problem. The [slab_allocator v0.3.5](https://github.com/weclaw1/slab_allocator) has been out of maintenance for 6 years.

Yes, we can fork the repo, but the published OSTD needs to depend on published crates. But we cannot publish `slab_allocator` and we do not want to publish `aster_slab_allocator`. Maybe we can simply copy the code from `slab_allocator`. With the license header, of course. This is a temporary solution anyway.

**Comment by sdww0** [comment]
@boterinas rerun

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
