### PR TITLE
Add .so files for LMbench-network

### PR DESCRIPTION
**Pull request by sdww0**
This PR adds several .so files that are required for network-related LMbench tests.

### CODE REVIEW

**Comment by tatetian** [comment]
Do you want to trigger the CI to build new Docker image?

**Comment by sdww0** [comment]
> Do you want to trigger the CI to build new Docker image?

No, since the .so files are already included in the Docker image.

**Comment by tatetian** [comment]
> > Do you want to trigger the CI to build new Docker image?
> 
> No, since the .so files are already included in the Docker image.

I was wrong. Thanks.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
