### PR TITLE
Fix the kernel page fault handler

### PR DESCRIPTION
**Pull request by lrh2000**
Address https://github.com/asterinas/asterinas/pull/672#discussion_r1536848178:

> I think that the page fault should _not_ be handled unless we have _verified_ that handling it is correct. So we should never use `debug_assert` here. At least we should use `assert`, and even explicitly using `panic` might be worthwhile.
> 
> This also means that, we should check the conditions under which handling page fault _is_ correct (e.g., the page fault address falls in some range), not exclude the situations where handling page faults is _not_ correct (e.g., the page fault address falls out of some range).
> 
> In the following code, this argument actually appears in the comments: `Safety: The page fault address has been checked`. However, the statement is simply not true since `debug_assert` is used here.
> 
> I would suggest adding a constant `PHYS_MEM_CAP_VADDR`, which is `PHYS_MEM_BASE_VADDR + N TiB`, and checking that the page fault address actually falls within this range.

I think this is a huge soundness hole, and I don't think it's acceptable that even the kernel page fault handler is only a temporary workaround.

This PR introduces `PHYS_MEM_VADDR_RANGE`, which describes the (maximum allowed) address range for direct mapping of physical memory, and checks in the page fault handler if the fault address actually falls within this range.

NOTE: https://github.com/asterinas/asterinas/pull/672#issuecomment-2016872939 is *not* addressed, so the newly added pages in the direct physical memory mapping are still on a per-process basis. As a temporary workaround, this is fine for me, so I leave it as is.

### CODE REVIEW

**Comment by lrh2000** [comment]
Unfortunately, this PR must have some conflicts with #713, sorry about that.

But I don't think #713 completely solves the problem, so there's still a point in making this PR.

**Comment by lrh2000** [comment]
Well, the OSDK test `osdk-doc-env-test` has timed out. I don't think it has anything to do with this PR.

**Comment by junyang-zh** [comment]
1. I agree with your point that the assertions shouldn't be debug assertions;
2. I agree that the the new mappings should be permanent. #713 fixes it;
3. I am unsure about the `PHYS_MEM_CAP_VADDR` design, adding it as a fix of a temporary fix seems ok.

**Comment by lrh2000** [comment]
@junyang-zh 

> 1\. I agree with your point that the assertions shouldn't be debug assertions;
>
> 2\. I agree that the the new mappings should be permanent. #713 fixes it;

Yes, as this PR only fixes the first problem, not the second.

> 3\. I am unsure about the `PHYS_MEM_CAP_VADDR` design

Perhaps you could elaborate? There are many things you may be unsure about. Do you have concerns about whether the constant should exist, the value the constant currently takes, the name of the constant, or the interaction of the constant with existing code?

**Comment by tatetian** [comment]
@sdww0 Any inputs for this PR?

**Comment by sdww0** [comment]
1. I agree to only create new mappings in the page fault handler and not allow any changes to existing mapping.
2. I agree that the page fault handler should not use debug assert.
3. My concern is that PR #672 is intended to solve the problem of missing high address (`0x7000_0000_7004`) mapping in VirtIO devices in the TDX environment, and this address is out of the 64TB range. Does the 64TB here include the MMIO region?

**Comment by lrh2000** [comment]
> My concern is that PR https://github.com/asterinas/asterinas/pull/672 is intended to solve the problem of missing high address (0x7000_0000_7004) mapping in VirtIO devices in the TDX environment, and this address is out of the 64TB range. Does the 64TB here include the MMIO region?

@sdww0 Thanks for this input.

Linux uses separate APIs to map memory for MMIO, such as [`io_mapping_create_wc`](https://www.kernel.org/doc/Documentation/io-mapping.txt). Thus, Linux sets the maximum size of direct mapping to 64 TiB, where the 64 TiB  does _not_ include the MMIO region.

Currently, Asterinas has no support for such APIs. So let's enlarge the maximum size of direct mapping as a temporary solution. I am going to increase it to 127 TiB (note the total size of the kernel virtual memory is only 128 TiB).

By the way, I also want to emphasize the following:

## Why `PHYS_MEM_MAPPING_MAX_SIZE` / `PHYS_MEM_VADDR_RANGE`?

It's very surprising to know that TDX MMIO uses such a high address. Having a constant representing the maximum size of the direct mapping (currently named `PHYS_MEM_MAPPING_MAX_SIZE`) makes these things explicitly documented, instead of hiding the details in the obscure `PHYS_MEM_BASE_ADDR..kernel_loaded_offset()` range.

Since the MMIO address is `0x7000_0000_7004`, we're trying to creating maps that are very close to the `kernel_loaded_offset()`:
```
   The start of the kernel virtual memory
   | <- PHYS_MEM_BASE_VADDR [0xffff_8000_0000_0000]
   | \
   |  | ~112 TiB
   | /
   | <- TDX MMIO address
   | \
   |  | ~15.998 TiB
   | /
   | <- kernel_loaded_offset() [0xffff_ffff_8000_0000]
   | \
   |  | 2 GiB
   | /
   The end of the kernel virtual memory
```

We nowhere document the maximum size of the direct mapping we expect, so we can only guess by calculating the distance between `PHYS_MEM_BASE_ADDR` and `kernel_loaded_offset()`. It's not obvious and a bit confusing, compared to explicitly having a constant representing the maximum size and explicitly documenting why we set the maximum size that way.

By having `PHYS_MEM_MAPPING_MAX_SIZE`, if someone wants to make adjustments to  `PHYS_MEM_BASE_ADDR` or `kernel_loaded_offset()`, they no longer have to worry about whether the direct mapping will be compromised due to wrong maximum size or overlap with the kernel code, because we always have a correct value for `PHYS_MEM_MAPPING_MAX_SIZE` and assert:
```rust
const_assert!(PHYS_MEM_VADDR_RANGE.end < kernel_loaded_offset());
```

**Comment by junyang-zh** [comment]
> Currently, Asterinas has no support for such APIs.

Note that @nishirong and me are working on it. We may soon have a PR addressing all the in-kernel vm mapping issues.

**Comment by lrh2000** [comment]
> Note that @nishirong and me are working on it. We may soon have a PR addressing all the in-kernel vm mapping issues.
> 
> After that, the kernel page fault handler may be discarded.

@junyang-zh Yes, we should remove the kernel page fault handler after we can properly map MMIO pages. I cannot agree more with that point. But I don't think we should ever introduce soundness holes. Not even in a temporary solution.

Moreover, I want to argue that the constant representing the maximum size of the direct mapping can be kept. This has the advantages mentioned in my comment above (although I'm using the high MMIO address as a motivating example, it's not really deeply coupled), and makes the kernel's virtual memory layout much clearer. It's not a temporary fix, IMO.

**Review by tatetian — APPROVED** [review]
I really appreciate your effort in making the code more robust and clear. I am merging this PR. Thanks for the contribution!

**Pull request merged**
