### PR TITLE
Make tests integration test run in parallel

### PR DESCRIPTION
**Pull request by StevenJiang1110**
Currently, all tests in the integration suite are executed sequentially. However, these tests are logically independent and can be run in parallel. Traditionally, if one test fails, all subsequent tests are skipped. With this pull request, each test will be executed independently.

The downside is that every test in the integration suite will require downloading a Docker image. Nonetheless, this does not appear to be a significant issue, as GitHub will execute all jobs in parallel.

### CODE REVIEW

**Comment by junyang-zh** [comment]
I think this PR is really welcoming since the integration test are getting longer and some of the tests are failing often. It is good to see if others can pass. Will we merge it sooner?

**Comment by tatetian** [comment]
@StevenJiang1110 Why two checks out of the nine are cancelled?

**Comment by StevenJiang1110** [comment]
@boterinas rerun

**Comment by tatetian** [comment]
@StevenJiang1110 Needs to be rebased

**Comment by StevenJiang1110** [comment]
This PR is rebased.

> @StevenJiang1110 Why two checks out of the nine are cancelled?

It seems it was caused by some random failures. Running CI again will not cancel these checks.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
