### PR TITLE
Run ktest by one of the kernels

### LINKED ISSUE #975: ktest as a kernel
### Summary

Well, I want to make ktest as a kernel built on top of aster-frame (OSTD), and run as a kernel. Currently the ktest crate is a dependency of aster-frame, which leads to many problems such as:
 - a lot of runtime needed when running ktest, which need to be passed as parameters #834 ;
 - need to pass cfg to aster-frame when rebuilding the test #974 ;

By making ktest a kernel depending on aster-frame, which has it's entrypoint as `#[aster_main]` (`#[ostd::main]`), it works for all the above problems.

### Proposal

Originally the dependency chain of testing a target crate `A` is:

```text
ktest <---------------- ostd <--- A <--- base_crate
                       /         / 
ktest_proc_macro <----'---------'
```

The proposed one is:

```text

        .-- ktest <----(if testing)----.
        v                               \
  .-- ostd <---------- A <--------- base_crate
  v                   /
ktest_proc_macro <---'
```

Instead of a conditional compilation to choose the ktest entry point at `aster_frame::boot::call_aster_main`, the ktest entry point should be registered as **STRONG** `#[aster_main]`, while other kernel's `#[aster_main]` should be WEAK. So during linking, if the ktest main exist ktests will be excecuted, other wise kernel main would be executed.

### PR DESCRIPTION
**Pull request by junyang-zh**
In this PR, the ktest subsystem is divided into `ostd-test` and `osdk-test-kernel`. The former provides definitions and the latter is a kernel to run the tests. The `ostk-test-kernel` should be published to let OSDK users to do tests.

The original dependency graph for crate `A` would be:

```
ktest <---------------- ostd <--- A <---- base_crate
                       /         / 
ktest_proc_macro <----'---------'
```

The updated one would be:

```
		          .---- osdk-test-kernel <---(if testing)---.
		         v                                           \
    ostd-macros <----- ostd <--------------- A <----------------- base_crate
                      /           
ostd-test <----------'
```

This PR also enable Cargo Clippy for ktests.

Fix #975 . #1137 needs it to provide kernel unit tests with a default page allocator. Prefer this over #1102 once ready. This PR also enables a more elegant implementation of #696, since the ktest runner can use all of the OSTD APIs now (previously implemented by #834 ).

The massive file move is done by the last commit, so it is recommended to read the patch by commits.

This is quite a **BREAKING** change, so once the naming of the runner crate is decided and the rest of the refactor is thoroughly discussed, I will publish the runner kernel and bump the version of OSDK and OSTD. The OSDK unit test and the publish check in CI will not be successful until then.

### CODE REVIEW

**Comment by junyang-zh** [comment]
@boterinas ready

**Comment by junyang-zh** [comment]
@tatetian After your review I may publish the `osdk-test-kernel` crate to make CI passing.

**Comment by tatetian** [comment]
I have no problem with this PR. Since this PR is doomed to conflict with almost all pending PRs, I will merge a few other PRs and then this one.

**Comment by junyang-zh** [comment]
Ok, I have inspected this PR again. All CI in https://github.com/asterinas/asterinas/pull/1159/commits/39ef0c6ea6046d1657e1eacea93a657f128bdc89 except 2 osdk tests failed because the test kernel is not published. After the version bump the test kernel would automatically be published. Re-run the CI minutes later after the merge of this PR should make everything fine.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
