### PR TITLE
Rename `cond()` to `try_op()`

### PR DESCRIPTION
**Pull request by lrh2000**
The `cond` in `wait_events` is confusing. We should choose a better name for it. Maybe `op` (short for "operation")?

I remembered that this caused some confusion when discussing the proposed changes in https://github.com/asterinas/asterinas/issues/1355 with @tatetian. Let's fix that.

### CODE REVIEW

**Comment by tatetian** [comment]
> The cond in wait_events is confusing. We should choose a better name for it. Maybe op (short for "operation")?

The name `op` is too vague. I think it is important to have `cond` in the name. After all, the method is a wait method and it is essential for its caller to specify a termination condition.

**Comment by lrh2000** [comment]
> The name `op` is too vague. I think it is important to have `cond` in the name. After all, the method is a wait method and it is essential for its caller to specify a termination condition.

The typical pattern is:
```rust
self.wait_events(IoEvents::IN, None, || self.try_read(writer))
```

The doc comments say it's "operation":
```rust
    /// Waits for events and performs event-based operations.
```

So do you have a better name for "try_read"/"try_write"/... e.t.c.? Is it "operation" or "condition" or both?

Anyway, I don't really have a strong opinion here, or if you think `cond` is good enough now, maybe you can just close this PR.

**Comment by tatetian** [comment]
Thanks for the explanation! You are right. The `op` name is better

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
