### PR TITLE
Reduce the kernel stack size in release mode

### PR DESCRIPTION
**Pull request by cchanging**
Initially, my thought was to specify `release_feature` under the profile.release condition, but it didn't work. @junyang-zh @StevenJiang1110 Do you think this is a suitable approach, and is it possible to achieve this functionality within osdk?

### CODE REVIEW

**Comment by StevenJiang1110** [comment]
How about using `cfg(debug_assertions)`,  as suggested by https://stackoverflow.com/questions/39204908/how-to-check-release-debug-builds-using-cfg-in-rust?

**Comment by cchanging** [comment]
> How about using cfg(debug_assertions), as suggested by https://stackoverflow.com/questions/39204908/how-to-check-release-debug-builds-using-cfg-in-rust?

This can be work for now, but debug_assertions != debug mode. One may do this to test the `debug_assertion` in release mode.
```rust
[profile.release]
debug = true
```

**Comment by StevenJiang1110** [comment]
> This can be work for now, but debug_assertions != debug mode. One may do this to test the debug_assertion in release mode.

Yes, this can be misleading for some times. 

[Another method mentioned in the community](https://users.rust-lang.org/t/conditional-compilation-for-debug-release/1098) is that we can add a `build.rs` for base crate(this can be done by OSDK), 

```rust
use std::env;

pub fn main() {
    if let Ok(profile) = env::var("PROFILE") {
        println!("cargo:rustc-cfg=build={:?}", profile);
    }
}
```

Then we can use 
```rust
#[cfg(build = "debug")]
fn do_something(){
    // Output sensitive debugging info
}

#[cfg(build = "release")]
fn do_something(){
    // Don't output anything
}
```

But this also has problems. It can only recognize built-in profile, if you have customized profile like `release-lto`, we must change our code accrodingly.
```rust
#[cfg(any(build = "release", build = "release-lto"))]
fn do_something(){
    // Don't output anything
}
```

**Comment by junyang-zh** [comment]
I don't know if the build script works with OSDK. It needs to be tested.

**Comment by cchanging** [comment]
The `build.rs` method can not work either. I finally decide to make the kernel stack size configurable, since the kernel stack size of the system developed by the OSDK user may vary significantly, so they need a method to set the kernel stack size in their OS.

**Review by tatetian — COMMENTED** [review]
## Big decisions

First of all, I agree that the kernel stack size should be provided by OSTD users, not determined by OSTD alone. This is obvious as the kernel stack usage is largely determined by the user kernel on top of OSTD. So we need to provide a way for the user to specify this value.

The next big design decision is whether this kernel stack size should be determined at compile or runtime. This one is obvious, too. From the kernel code itself, we should be able to determine the maximum kernel stack usage. So the kernel stack size should not be given as a runtime parameter, as proposed by this PR, which adds unnecessary code complexity and runtime overhead.

**In short, the kernel stack size should be provided by OSTD _users_ and determined at _compile_ time.**

Assuming that we are the same page regarding the two big design decisions, we can discuss the concrete implementation. There are two options.

## Option 1

Since we have `OSDK.toml`, I think that is the most natural place to specify the kernel stack size. So I am thinking of adding a new field to `OSDK.toml`.

```toml
[build]
kstack_nr_pages = 4
```

Ideally, we want to support the following syntax to specify different kernel stack sizes depending on the build profile.

```toml
[build.debug]
kstack_nr_pages = 128

[build.release]
kstack_nr_pages = 8
```

But `OSDK.toml` does not support this ability of switching parameters according to build profiles. And we need to modify OSDK to support this field.

## Option 2

Another approach to specify the compile-time parameter is via `env` or `opt_env`.

```rust
/// The kernel stack size of a task, specified in pages.
///
/// By default, we choose a rather large stack size.
/// OSTD users can choose a smaller size by specifying
/// the `OSTD_TASK_STACK_SIZE_IN_PAGES` environment variable
/// at build time.
pub static STACK_SIZE_IN_PAGES: u32 = option_env!("OSTD_TASK_STACK_SIZE_IN_PAGES")
    .and_then(|env_str| env_str.parse::<u32>().ok())
    .unwrap_or(DEFAULT_STACK_SIZE_IN_PAGES);

/// The default kernel stack size of a task, specified in pages.
pub const DEFAULT_STACK_SIZE_IN_PAGES: u32 = 128;

const fn parse_u32(input: &str) -> u32 {
    let mut output: u32 = 0;
    let bytes = input.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        let digit = (bytes[i] - b'0') as u32;
        output = output * 10 + digit;
        i += 1;
    }
    output
}
```

## Conclusion

I prefer Option 2, which is short and sweet for our most urgent demand, which is to optimize the performance of Asterinas. In the long term, we will have to provide a user-friendly way to specify kernel stack sizes. From this angle, Option 1 is more preferable.

**Comment by cchanging** [comment]
@boterinas rerun

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
