### PR TITLE
Optimize trim methods in `Vmar`.

### PR DESCRIPTION
**Pull request by cchanging**
Do some optimizations for trim methods in `Vmar` which will benefit for fork+exec test.

### CODE REVIEW

**Comment by grief8** [comment]
@boterinas assign @cchanging

**Comment by grief8** [comment]
@boterinas ready

**Comment by cchanging** [comment]
@boterinas rerun

**Comment by grief8** [comment]
@boterinas label O-refactor

**Comment by cchanging** [comment]
@boterinas label -O-refactor

**Comment by grief8** [comment]
@boterinas rerun

**Comment by grief8** [comment]
@boterinas rerun

**Comment by grief8** [comment]
@boterinas rerun

**Comment by grief8** [comment]
@boterinas rerun

**Comment by grief8** [comment]
@boterinas rerun

**Comment by grief8** [comment]
@boterinas rerun

**Comment by grief8** [comment]
@boterinas blocked

**Comment by grief8** [comment]
@boterinas ready

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
