### PR TITLE
Add syscall `getpgid`

### PR DESCRIPTION
**Pull request by ZephyrZhang3**

### CODE REVIEW

**Review by tatetian — COMMENTED** [review]
The code looks good. Thanks for contributing to Asterinas.

Could you also update [the Linux compatibility page](https://github.com/asterinas/asterinas/blob/main/docs/src/kernel/linux-compatibility.md) of the Asterinas book, adding the `gpid` system call?

**Comment by ZephyrZhang3** [comment]
ok

**Comment by ZephyrZhang3** [comment]
The x86 syscall table has already been listed in the doc, is there a riscv syscall table to make sure the syscall number?

**Comment by YanWQ-monad** [comment]
> The x86 syscall table has already been listed in the doc, is there a riscv syscall table to make sure the syscall number?

It's 155. For a quick reference, you can have a look at https://jborza.com/post/2021-05-11-riscv-linux-syscalls.

**Comment by ZephyrZhang3** [comment]
> In addition, could you try to add gvisor tests for the new system call?

Are there any references about gvisor testing in this project? I haven't found them and figured out how to do this test yet.
Or what I should do is just adding code `getpgid_test \` in the file `test/syscall_test/Makefile`?

```
futex_test \
getdents_test \
getpgid_test \    // <= add this line
ioctl_test \
```

**Comment by ZephyrZhang3** [comment]
> In addition, could you try to add gvisor tests for the new system call?

I looked at the [syscall test framework](https://github.com/asterinas/asterinas/blob/main/test/syscall_test/Makefile#L3) and found that the syscall tests are in the [gVisor repo](https://github.com/asterinas/gvisor.git).

However, in the entire gVisor project, there is only calls to `getpgid(0)` (i.e., same as `getpgrp()`) in one test file (`gvisor/test/syscalls/linux/pty.cc`). There is no direct test for `getpgid`.

Therefore, I should write a new test file(`gvisor/test/syscalls/linux/getgpid.cc`) and PR to [gVisor repo](https://github.com/asterinas/gvisor.git).

Did I understand it wrong or am I missing something?
image

**Comment by tatetian** [comment]
> There is no direct test for getpgid.

Ok. Maybe gvisor developers think getpgid is too simple to test 😅

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
