### PR TITLE
Fix a concurrency bug in clocksource

### LINKED ISSUE #1160: Chance of subtraction overflow in clocksource
### Describe the bug

A job not related to the clock source implementation failed.

https://github.com/asterinas/asterinas/actions/runs/10372263948/job/28714585105

```
 [ RUN      ] ClockGettime/MonotonicVDSOClockTest.IsCorrect/CLOCK_MONOTONIC
panicked at /__w/asterinas/asterinas/kernels/comps/time/src/clocksource.rs:97:32:
attempt to subtract with overflow
```

https://github.com/asterinas/asterinas/blob/be54a39592ff60fae6e729abaa3d4a26dd7f5624/kernel/comps/time/src/clocksource.rs#L94-L102

### To Reproduce

Very rare. May not be reproducible locally.

### PR DESCRIPTION
**Pull request by cchanging**
Fix #1160

I speculate that the issue is caused by prematurely releasing the lock on `last_record`. I need to attempt several CI runs to see if the bug is still triggered.

### CODE REVIEW

**Comment by cchanging** [comment]
@boterinas rerun

**Comment by cchanging** [comment]
@boterinas rerun

**Comment by cchanging** [comment]
@boterinas rerun

**Comment by cchanging** [comment]
@boterinas ready

**Comment by tatetian** [comment]
@boterinas rerun

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
