### PR TITLE
Update multiboot2 version

### PR DESCRIPTION
**Pull request by Marsman1996**
Update `multiboot2` version since 0.20.2 is yanked.

https://crates.io/crates/multiboot2/versions

### CODE REVIEW

**Comment by Marsman1996** [comment]
Why publish failed🤔

**Comment by junyang-zh** [comment]
> Why publish failed🤔

```
 error: failed to select a version for the requirement `multiboot2 = "^0.20.2"`
candidate versions found which didn't match: 0.23.0, 0.22.2, 0.22.1, ...
location searched: crates.io index
required by package `ostd v0.8.2`
    ... which satisfies dependency `ostd = "^0.8.2"` of package `osdk-test-kernel v0.8.2 (/__w/asterinas/asterinas/target/package/osdk-test-kernel-0.8.2)`
```

`osdk-test-kernel` 's dependency of OSTD still goes to crates.io in the publish check. Needs further investigation.

**Comment by junyang-zh** [comment]
I see. Only when the version is bumped the publish failure can go away. We can ignore this failure. For yanked upstream, there's nothing we can do about it but yanking ours.

**Review by junyang-zh — COMMENTED** [review]
Looks good to me. The next step is to bump the version by a patch using `tools/bump_version.sh patch` and commit all the changes. @Marsman1996 you can do it in this PR. I believe it fixes the pervasive CI failures. Then we would consider yanking 0.8.2.

**Comment by Marsman1996** [comment]
Bump version to 0.8.3

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
