### PR TITLE
(How to) Work around a subtle bug in GRUB (?)

### PR DESCRIPTION
**Pull request by lrh2000**
The CI failure in #1647 is subtle. #1689 should be a valid fix, but unfortunately it does not address the exact cause of the CI failure.

Meanwhile, it's not really easy to debug further, because we don't even have a valid RIP dumped by the CPU exception, and it involves too much about GRUB internals (e.g., `grub-mkrescue` rewrites a `kernel.img` into a symbol-less `bootx64.efi`, and GRUB contains modules that are loaded at runtime).

We have to guess something, e.g. the cause of the CPU exception is that it calls a NULL function pointer and then steps forward to address 201E/201F. Luckily, it's true so we get a clue to recover the backtrace.

The result of the recovered backtrace is the following patch. Please read the commit messages to see exactly what happens:
```patch
From 618fb9ee9d68cda43dfd8a6c439781fea7215cbe Mon Sep 17 00:00:00 2001
From: Ruihan Li <lrh2000@pku.edu.cn>
Date: Fri, 13 Dec 2024 22:02:31 +0800
Subject: [PATCH] Reset grub_mm_add_region_fn after exiting EFI services

Currently, EFI services can be used after they are exited because we
allocate memory after exiting EFI services.

An example call stack is:

  grub_multiboot_boot
    grub_multiboot2_make_mbi
      grub_efi_finish_boot_services
        b->exit_boot_services
    normal_boot
      grub_relocator32_boot
        grub_relocator_alloc_chunk_align_safe
          grub_relocator_alloc_chunk_align
            grub_malloc
              grub_memalign
                grub_mm_add_region_fn
                [= grub_efi_mm_add_regions]
                  grub_efi_allocate_any_pages
                    grub_efi_allocate_pages_real
                      b->allocate_pages

This can lead to confusing errors. After exiting EFI services,
b->allocate_pages may point to the NULL address, resulting in something
like:

!!!! X64 Exception Type - 01(#DB - Debug)  CPU Apic ID - 00000000 !!!!
RIP  - 000000000000201F, CS  - 0000000000000038, RFLAGS - 0000000000200002
RAX  - 000000007F9EE010, RCX - 0000000000000001, RDX - 0000000000000002
RBX  - 0000000000000006, RSP - 00000000001CFBEC, RBP - 0000000000000000
RSI  - 0000000000000000, RDI - 00000000FFFFFFFF
R8   - 0000000000000006, R9  - 000000007FEDFFB8, R10 - 0000000000000000
R11  - 0000000000000475, R12 - 0000000000000001, R13 - 0000000000000002
R14  - 00000000FFFFFFFF, R15 - 000000007E432C08
DS   - 0000000000000030, ES  - 0000000000000030, FS  - 0000000000000030
GS   - 0000000000000030, SS  - 0000000000000030
CR0  - 0000000080010033, CR2 - 0000000000000000, CR3 - 000000007FC01000
CR4  - 0000000000000668, CR8 - 0000000000000000
DR0  - 0000000000000000, DR1 - 0000000000000000, DR2 - 0000000000000000
DR3  - 0000000000000000, DR6 - 00000000FFFF0FF0, DR7 - 0000000000000400
GDTR - 000000007F9DE000 0000000000000047, LDTR - 0000000000000000
IDTR - 000000007F470018 0000000000000FFF,   TR - 0000000000000000
FXSAVE_STATE - 00000000001CF840

Ideally, we would like to avoid all memory allocations after exiting EFI
services altogether, but that requires significant code changes. This
patch suggests a simple workaround that resets grub_mm_add_region_fn
after exiting EFI services, so:

 - Memory allocations after exiting EFI services have a better chance of
   success because grub_memalign will try to reclaim the disk cache if
   it sees a NULL grub_mm_add_region_fn.

 - At worst, it will fail to allocate memory after exiting EFI services,
   but it will explicitly tell users that it's out of memory, which is
   still much better than the current situation where it fails in a
   fairly random way and triggers a CPU exception.

Signed-off-by: Ruihan Li <lrh2000@pku.edu.cn>
---
 grub-core/kern/efi/mm.c | 6 ++++++
 1 file changed, 6 insertions(+)

diff --git a/grub-core/kern/efi/mm.c b/grub-core/kern/efi/mm.c
index bc97ecd47..15c35e0ce 100644
--- a/grub-core/kern/efi/mm.c
+++ b/grub-core/kern/efi/mm.c
@@ -297,6 +297,12 @@ grub_efi_finish_boot_services (grub_efi_uintn_t *outbuf_size, void *outbuf,
   if (efi_desc_version)
     *efi_desc_version = finish_desc_version;
 
+  /*
+   * We cannot request new memory regions from the EFI services anymore.
+   * FIXME: Can we completely avoid memory allocations after this?
+   */
+  grub_mm_add_region_fn = NULL;
+
 #if defined (__i386__) || defined (__x86_64__)
   if (is_apple)
     stop_broadcom ();
-- 
2.47.1
```

As I said in the commit message, this isn't a complete fix, but a workaround that reduces the chance of a failed boot and prints a reasonable message when it does fail.

However, I have no way to verify that the patch actually helps, because whether the boot fails is strongly related to whether the remaining heap space after exiting EFI services is enough to allocate some strutures. This is highly unstable across different GRUB builds, so whether I build GRUB myself or [build GRUB in the CI machine](https://github.com/asterinas/asterinas/pull/1706) _without the above patch_, the problem immediately disappears.

So what should I do?
 1. Do nothing. Then #1647 will be blocked until this problem goes away, e.g. when we do the next Docker version bump (likely), or when the upstream fixes the problem (unlikely in the short term).
 2. Do a dummy Docker version bump. This will trigger the GRUB rebuild, so the problem will (probably) go away.
   - We had [a version bump on December 7th](https://github.com/asterinas/asterinas/commit/00e3688aa8945e09a48e85013ab73900490db7ad), but [it reused cached steps and no GRUB rebuild was triggered](https://github.com/asterinas/asterinas/actions/runs/12212337095/job/34070677051).
 3. Do a Docker version bump that includes the above GRUB patch when we rebuild GRUB. However,
   - This patch will probably migrate the problem, but I cannot verify this.
   - How do I get this patch into the Docker build process? I don't think it's a good idea to include it directly in the Dockerfile.
      - Is there a better way? Download from the GitHub repo (but need to push the patch to the repo first)?

### CODE REVIEW

**Comment by junyang-zh** [comment]
Will it be better if we upgrade from grub-2.12-rc to the stable release of 2.12?

**Comment by lrh2000** [comment]
> Will it be better if we upgrade from grub-2.12-rc to the stable release of 2.12?

Sorry? I don't understand what you want to mean here.

If I understand our current Dockerfile correctly, we're already using grub-2.12. Meanwhile, grub-2.12 is the latest release so we cannot bump it further.

https://github.com/asterinas/asterinas/blob/18d5eb1f02825ce80cefc8a9c09e6931a0c2ac9e/tools/docker/Dockerfile.jinja#L311

And bumping the version won't solve the problem, because the problem exists in GRUB's mainline repository as well.

But bumping the version (if possible) can be a way to force GRUB to rebuild. Perhaps your original intent is to suggest a way to force GRUB to rebuild? (Even if it does not work as described above).

**Comment by junyang-zh** [comment]
> > Will it be better if we upgrade from grub-2.12-rc to the stable release of 2.12?
> 
> Sorry? I don't understand what you want to mean here.

Ah. Sorry. I said that because of a slip of memory. When I added GRUB I used 2.12-rc1 and the stable release wasn't available yet. Later it was upgraded but I forgot. So I suggested to upgrade it but it was already upgraded. You could forget about what I said.

**Comment by tatetian** [comment]
@lrh2000 Thanks for investigating this bug! I really appreciate that. But I don't fully understand your points.

> Do a dummy Docker version bump. This will trigger the GRUB rebuild, so the problem will (probably) go away.
We had [a version bump on December 7th](https://github.com/asterinas/asterinas/commit/00e3688aa8945e09a48e85013ab73900490db7ad), but [it reused cached steps and no GRUB rebuild was triggered](https://github.com/asterinas/asterinas/actions/runs/12212337095/job/34070677051).

So the yet-to-be-confirmed "bug" exists in the mainstream GRUB. Why rebuilding GRUB will probably make the problem go way? A rebuild GRUB will still contain the bug.

And what makes you say that "December 7th version bump uses the cached steps and no GRUB rebuild was triggered"? The CI log did includes GRUB rebuild messages.

> #35 [grub 2/7] RUN wget -O grub.tar.xz https://ftp.gnu.org/gnu/grub/grub-2.12.tar.xz     && mkdir /root/grub     && tar xf grub.tar.xz --strip-components=1 -C /root/grub     && rm grub.tar.xz
#35 0.137 --2024-12-07 11:03:49--  https://ftp.gnu.org/gnu/grub/grub-2.12.tar.xz
#35 0.137 Resolving ftp.gnu.org (ftp.gnu.org)... 209.51.188.20, 2001:470:142:3::b
#35 0.161 Connecting to ftp.gnu.org (ftp.gnu.org)|209.51.188.20|:443... connected.

And let's assume that December 7th version bump did used the cached steps, why this version bump PR won't?

**Comment by tatetian** [comment]
@lrh2000 And by the way, I was surprised that the root cause of this failure is due to a bug in GRUB. I suppose that GRUB is quite a mature and stable project. And I don't think Asterinas is using any cool new, unstable features of GRUB. So I am wondering why it is _us_ who encounters and reports the bug for the first time?

**Comment by lrh2000** [comment]
> So the yet-to-be-confirmed "bug" exists in the mainstream GRUB. Why rebuilding GRUB will probably make the problem go way? A rebuild GRUB will still contain the bug.

This is mainly because I've tried to reproduce the problem with the following settings (in order to obtain a chance to verify if my patch helps):
 - I have rebuilt GRUB locally (without applying any patch), but the problem goes away.
 - I have [rebuilt GRUB in our CI workflow (without applying any patch)](https://github.com/asterinas/asterinas/actions/runs/12318663769/job/34383908161), but the problem goes away.

From my understanding of this BUG, it is reasonable to expect it to be highly unstable because it depends on the heap layout. So, it's fully possible for two different GRUB builds that result in different heap layouts.

The final steps before GRUB jumps to the loaded kernel are roughly:
 1. Exit the EFI boot services.
 2. Do some allocations.
 3. Jump to the loaded kernel.

If all the allocations in step 2 do not exhaust GRUB's heap space, everything will work normally. However, if the heap is exhausted, it will ask the EFI boot services for more memory, but this will fail because the EFI services have been exited.

 - The point is, it's pretty hard to guarantee (or even predict) that these allocations will fit into the remaining heap space, which depends on too many things.

> And what makes you say that "December 7th version bump uses the cached steps and no GRUB rebuild was triggered"? The CI log did includes GRUB rebuild messages.
> 
> > #35 [grub 2/7] RUN wget -O grub.tar.xz https://ftp.gnu.org/gnu/grub/grub-2.12.tar.xz     && mkdir /root/grub     && tar xf grub.tar.xz --strip-components=1 -C /root/grub     && rm grub.tar.xz
> > #35 0.137 --2024-12-07 11:03:49--  https://ftp.gnu.org/gnu/grub/grub-2.12.tar.xz
> > #35 0.137 Resolving ftp.gnu.org (ftp.gnu.org)... 209.51.188.20, 2001:470:142:3::b
> > #35 0.161 Connecting to ftp.gnu.org (ftp.gnu.org)|209.51.188.20|:443... connected.
> 
> And let's assume that December 7th version bump did used the cached steps, why this version bump PR won't?

Correct. I must have done something wrong when I checked the CI logs. Apologize for my misstatement.

> And by the way, I was surprised that the root cause of this failure is due to a bug in GRUB. I suppose that GRUB is quite a mature and stable project. And I don't think Asterinas is using any cool new, unstable features of GRUB. So I am wondering why it is _us_ who encounters and reports the bug for the first time?

That's a good point. More seriously, I've been looking at the Linux boot protocol implementation in GRUB, and it literally has the exact same problem.
 - Given the large number of users who boot Linux using GRUB (in UEFI environments), it's very odd that we're the first to run into this problem.

I'll send the patch and bug report to the GRUB mailing list on Monday. We can see how the GRUB folks respond. Other than that, I really don't know what else I can do.

**Comment by tatetian** [comment]
@lrh2000 Thanks for the clarification!

> I'll send the patch and bug report to the GRUB mailing list on Monday

That's good to hear. Let's see how the GRUB guys respond.

> it is reasonable to expect it to be highly unstable because it depends on the heap layout.

This statement is surprising to me. Although I cannot claim that the building process is a completely deterministic one, it should be deterministic enough that the same bug can be reproduced on the different builds of the same program. Could you elaborate on how the build process may affect the so-called "heap layout"?

Lastly, do you think that it is worth a try to bump the version? I still can't see why building GRUB is going to help...

**Comment by lrh2000** [comment]
> This statement is surprising to me. Although I cannot claim that the building process is a completely deterministic one, it should be deterministic enough that the same bug can be reproduced on the different builds of the same program. Could you elaborate on how the build process may affect the so-called "heap layout"?

I'm trying to figure out what the difference is between my local GRUB build and the Docker GRUB build.

If I figure it out later, I'll answer this question.

> Lastly, do you think that it is worth a try to bump the version? I still can't see why building GRUB is going to help...

Since the December 7th version bump does not help, I guess no.

However, I think it might be worth trying if my patch helps, if you think it's okay to put it in the repo and reference it in the docker build process (if it turns out to be useless later, we can just revert the commit). 

Otherwise, if you want to wait for confirmation from the GRUB maintainers and then make a decision, that's fine but I don't know how long that will take.

**Comment by tatetian** [comment]
> I think it might be worth trying if my patch helps, if you think it's okay to put it in the repo and reference it in the docker build process

Sure. I am totally ok with creating a forked repo for GRUB with your patch. But the problem is that ...

> whether I build GRUB myself or https://github.com/asterinas/asterinas/pull/1706 without the above patch, the problem immediately disappears.

Your experiment has shown that the problem disappeared with or without your patch.

**Comment by lrh2000** [comment]
@tatetian 

> > This statement is surprising to me. Although I cannot claim that the building process is a completely deterministic one, it should be deterministic enough that the same bug can be reproduced on the different builds of the same program. Could you elaborate on how the build process may affect the so-called "heap layout"?
> 
> I'm trying to figure out what the difference is between my local GRUB build and the Docker GRUB build.
> 
> If I figure it out later, I'll answer this question.

I have found that the main difference exists in several unrelated modules. I think they are caused by some auto-detecting configurations (e.g. `./configure` can automatically enable/disable some features if it can/cannot detect some dependencies).

<details>
<summary> Difference details </summary>

 - `bad.ls` uses the Docker GRUB build.
 - `good.ls` uses my local GRUB build.

Note that the `font.mod`/`normal.mod` is 2K/8K smaller. The differences are large enough to change the heap layout.

```diff
diff --git a/bad.ls b/good.ls
index 5f429e0..ecdd1f4 100644
--- a/bad.ls
+++ b/good.ls
@@ -114,7 +114,7 @@
 -r--r--r-- 1 root root     8848 ./boot/grub/x86_64-efi/fat.mod
 -r--r--r-- 1 root root    26808 ./boot/grub/x86_64-efi/file.mod
 -r--r--r-- 1 root root     2952 ./boot/grub/x86_64-efi/fixvideo.mod
--r--r--r-- 1 root root    19840 ./boot/grub/x86_64-efi/font.mod
+-r--r--r-- 1 root root    17168 ./boot/grub/x86_64-efi/font.mod
 -r--r--r-- 1 root root     4528 ./boot/grub/x86_64-efi/fshelp.mod
 -r--r--r-- 1 root root      219 ./boot/grub/x86_64-efi/fs.lst
 -r--r--r-- 1 root root    46872 ./boot/grub/x86_64-efi/functional_test.mod
@@ -152,7 +152,7 @@
 -r--r--r-- 1 root root     8464 ./boot/grub/x86_64-efi/hashsum.mod
 -r--r--r-- 1 root root    10576 ./boot/grub/x86_64-efi/hdparm.mod
 -r--r--r-- 1 root root     1888 ./boot/grub/x86_64-efi/hello.mod
--r--r--r-- 1 root root     4072 ./boot/grub/x86_64-efi/help.mod
+-r--r--r-- 1 root root     4080 ./boot/grub/x86_64-efi/help.mod
 -r--r--r-- 1 root root     4616 ./boot/grub/x86_64-efi/hexdump.mod
 -r--r--r-- 1 root root    10448 ./boot/grub/x86_64-efi/hfs.mod
 -r--r--r-- 1 root root     4328 ./boot/grub/x86_64-efi/hfspluscomp.mod
@@ -212,7 +212,7 @@
 -r--r--r-- 1 root root    84168 ./boot/grub/x86_64-efi/net.mod
 -r--r--r-- 1 root root     4648 ./boot/grub/x86_64-efi/newc.mod
 -r--r--r-- 1 root root    10352 ./boot/grub/x86_64-efi/nilfs2.mod
--r--r--r-- 1 root root   178928 ./boot/grub/x86_64-efi/normal.mod
+-r--r--r-- 1 root root   170472 ./boot/grub/x86_64-efi/normal.mod
 -r--r--r-- 1 root root     5768 ./boot/grub/x86_64-efi/ntfscomp.mod
 -r--r--r-- 1 root root    16432 ./boot/grub/x86_64-efi/ntfs.mod
 -r--r--r-- 1 root root     4464 ./boot/grub/x86_64-efi/odc.mod
@@ -323,7 +323,7 @@
 -r--r--r-- 1 root root    58808 ./boot/grub/x86_64-efi/zfs.mod
 -r--r--r-- 1 root root    81880 ./boot/grub/x86_64-efi/zstd.mod
 -r--r--r-- 1 root root 31232423 ./boot/initramfs.cpio.gz
--r--r--r-- 1 root root        0 ./.disk/2024-12-15-09-38-13-00.uuid
+-r--r--r-- 1 root root        0 ./.disk/2024-12-15-09-41-11-00.uuid
 -r--r--r-- 1 root root   208896 ./efi/boot/bootx64.efi
 -r--r--r-- 1 root root  2949120 ./efi.img
 -r--r--r-- 1 root root        0 ./mach_kernel
```

</details>

But fortunately, as mentioned above, they are in _unrelated_ modules, so I can isolate them from the boot experiments.

I tried this:
 - In the unmodified Docker environment, I used `grub-mkrescue` to create `bad.iso`, which fails to boot due to the GRUB bug.
 - I rebuilt GRUB locally _without applying my patch_ and overwrote `/usr/local/grub/lib/grub/x86_64-efi/kernel.img` with the rebuilt `kernel.img`. I then used `grub-mkrescue` to create `baseline.iso`, which also fails to boot.
 - I _applied_ my patch and built GRUB locally. Then I overwrote `/usr/local/grub/lib/grub/x86_64-efi/kernel.img` with the rebuilt `kernel.img` (which contains the `grub_efi_finish_boot_services` method where my patch takes effect). Then I used `grub-mkrescue` to create `good.iso`, **which booted successfully!**

<details>
<summary> Difference details </summary>

 - `baseline.iso` is created using the `kernel.img` of my locally built unpatched GRUB.
   - This cannot boot.
 - `patch.iso` is created using the `kernel.img` of my locally built patched GRUB.
   - This can boot.
 - All other GRUB modules are built for the original Docker image.

Since the patch is small enough, there's no diff in the `ls -al` output, but it certainly changes the `md5sum` output.

```diff
diff --git a/baseline.ls b/patch.ls
index fb92d76..a09c308 100644
--- a/baseline.ls
+++ b/patch.ls
@@ -323,7 +323,7 @@
 -r--r--r-- 1 root root    58808 ./boot/grub/x86_64-efi/zfs.mod
 -r--r--r-- 1 root root    81880 ./boot/grub/x86_64-efi/zstd.mod
 -r--r--r-- 1 root root 31232423 ./boot/initramfs.cpio.gz
--r--r--r-- 1 root root        0 ./.disk/2024-12-15-10-06-36-00.uuid
+-r--r--r-- 1 root root        0 ./.disk/2024-12-15-10-09-45-00.uuid
 -r--r--r-- 1 root root   208896 ./efi/boot/bootx64.efi
 -r--r--r-- 1 root root  2949120 ./efi.img
 -r--r--r-- 1 root root        0 ./mach_kernel
```

```diff
diff --git a/baseline.md5 b/patch.md5
index d182f70..4708e48 100644
--- a/baseline.md5
+++ b/patch.md5
@@ -323,11 +323,11 @@ cc41b53a496aa69f4765c5ca7fb18f47  ./boot/grub/x86_64-efi/zfscrypt.mod
 ee1eb76f21b9ee38a500b4054db38ce8  ./boot/grub/x86_64-efi/zstd.mod
 cdec910bfa0b138ab995883bf94c80e6  ./boot/initramfs.cpio.gz
 56604219a31c4c663f3ec3d17df16614  ./boot.catalog
-286e78f69ff7744857fa56f123043ac4  ./efi/boot/bootx64.efi
-4037eb382ce89511867f4e94f629bf40  ./efi.img
+41e5bdebdebd658ca146d54555b33b73  ./efi/boot/bootx64.efi
+01693cc999f8fc60c4141f11463f43e9  ./efi.img
 d41d8cd98f00b204e9800998ecf8427e  ./mach_kernel
-286e78f69ff7744857fa56f123043ac4  ./System/Library/CoreServices/boot.efi
+41e5bdebdebd658ca146d54555b33b73  ./System/Library/CoreServices/boot.efi
 ab1af1e36f54404d00f29cbb8a66acfa  ./System/Library/CoreServices/SystemVersion.plist
 068bf8418823336ee1b48400b6225b0b  ./System/Library/CoreServices/.disk_label
 aa74a7b584f80f4ada0732c964a8292b  ./System/Library/CoreServices/.disk_label.contentDetails
-d41d8cd98f00b204e9800998ecf8427e  ./.disk/2024-12-15-10-06-36-00.uuid
+d41d8cd98f00b204e9800998ecf8427e  ./.disk/2024-12-15-10-09-45-00.uuid
```

</details>

> > whether I build GRUB myself or #1706 without the above patch, the problem immediately disappears.
> 
> So I am not sure that whether building the GRUB with your patch is useful or not...

So, I believe this comment is resolved, right?

**Comment by grief8** [comment]
It is indeed peculiar that today's [benchmark workflow](https://github.com/asterinas/asterinas/actions/runs/12341838143/) did not encounter the same issue while yesterday's did. This leads me to believe that there might be an error or inconsistency in our current codebase. Specifically, #1684 was merged just yesterday, and it involves significant modifications to the OSDK. I am uncertain whether these changes will take effect under your cases @lrh2000 .

**Comment by lrh2000** [comment]
> It is indeed peculiar that today's [benchmark workflow](https://github.com/asterinas/asterinas/actions/runs/12341838143/) did not encounter the same issue while yesterday's did. This leads me to believe that there might be an error or inconsistency in our current codebase. Specifically, #1684 was merged just yesterday, and it involves significant modifications to the OSDK. I am uncertain whether these changes will take effect under your cases @lrh2000 .

@grief8 Thanks for the information. As I said, this issue is very much dependent on GRUB's heap layout. Specifically, I think it's related to at least (i) the size of the kernel image, (ii) the size of the initramfs image, (iii) [configurations used to build GRUB](https://github.com/asterinas/asterinas/pull/1710#issuecomment-2543795999).

I took a very quick look at #1684, but I'm not sure it's related. However, I think there are a number of ways to resize the kernel image and the initramfs image. So merging any PR may make the problem disappear or reappear.

**Comment by tatetian** [comment]
@lrh2000 Great work! Then, I believe there is sufficient evidence that we can and should work around the annoying boot failure with this GRUB patch, before figuring out the root cause (e.g. why Asterinas is the first to encounter this problem and why the bug is triggered by Asterinas from commits to commits).

Could you fork a GRUB repo under the Asterinas organization and apply your patch?

**Comment by lrh2000** [comment]
> figuring out the root cause (e.g. why Asterinas is the first to encounter this problem and why the bug is triggered by Asterinas from commits to commits).

I have no idea how to answer these questions. But FYI, I've sent the patch to the GRUB mailing list: https://lore.kernel.org/grub-devel/20241216042708.749547-2-lrh2000@pku.edu.cn/T/#u

> Could you fork a GRUB repo under the Asterinas organization and apply your patch?

GRUB does not have an active mirror on GitHub (at least I cannot find one), so I cannot fork a repo. 

I created [asterinas/grub](https://github.com/asterinas/grub) directly from the [GRUB upstream](https://savannah.gnu.org/git/?group=grub) using the [GitHub importer](https://docs.github.com/en/migrations/importing-source-code/using-github-importer/about-github-importer).

The default branch `asterinas/2.12` is the grub 2.12 release (the `grub-2.12` tag) plus my patch.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
