### PR TITLE
Add syscall chroot

### PR DESCRIPTION
**Pull request by Plucky923**

### CODE REVIEW

**Review by tatetian — COMMENTED** [review]
Good job on adding the new system call! The changes look good. I have two requests. 
1. Could you also update "Linux Compatibility" page of the Asterinas Book and mark the chroot system call as supported?
2. Could you add a test case for the system call? The preferable approach is to enable existing gvisor test cases by editing `regression/syscall_test/Makefile`. In the unlikely situation that gvisor test suite does not include a chroot test, add a manually-written test program under `regression/apps`.

**Comment by Plucky923** [comment]
Thanks for your reminder! I have updated "Linux Compatibility" page and added test for chroot. But gvisor test cases for chroot require syscall capget. So I added test cases to blocklist.

**Comment by Plucky923** [comment]
> Good job on adding the new system call! The changes look good. I have two requests. 
> 1. Could you also update "Linux Compatibility" page of the Asterinas Book and mark the chroot system call as supported?
> 2. Could you add a test case for the system call? The preferable approach is to enable existing gvisor test cases by editing `regression/syscall_test/Makefile`. In the unlikely situation that gvisor test suite does not include a chroot test, add a manually-written test program under `regression/apps`.

Thanks for your reminder! I have updated "Linux Compatibility" page and added test for chroot. But gvisor test cases for chroot require syscall capget. So I added test cases to blocklist.

**Comment by lrh2000** [comment]
Not related to the changes, but I think we're now adopting a "rebase workflow". This means that we should probably avoid merge commits in PR.

We do not have a contribution guide at the moment, but you can look at the [No-Merge Policy](https://rustc-dev-guide.rust-lang.org/git.html?highlight=rebase#no-merge-policy) in the Rust Compiler Development Guide to see how to do this.

**Comment by Plucky923** [comment]
> Not related to the changes, but I think we're now adopting a "rebase workflow". This means that we should probably avoid merge commits in PR.
> 
> We do not have a contribution guide at the moment, but you can look at the [No-Merge Policy](https://rustc-dev-guide.rust-lang.org/git.html?highlight=rebase#no-merge-policy) in the Rust Compiler Development Guide to see how to do this.

Thanks for your reminder! When I submitted the PR, I was thinking about how to handle the merge commit. Thanks for your advice!

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
