### PR TITLE
Add missing TLB flushes to `VmSpace`

### PR DESCRIPTION
**Pull request by lrh2000**
The offending path that causes the problem that occurs in https://github.com/asterinas/asterinas/pull/811 and https://github.com/asterinas/asterinas/pull/829 is:
 - `VmMappingInner::write_bytes` -> `VmMappingInner::handle_page_fault` -> `VmMappingInner::map_one_page` -> `VmSpace::unmap`/`VmSpace::map`.
https://github.com/asterinas/asterinas/blob/07fbbcfd8c22459719c9af7eeeb3dee5ad24ba92/kernel/aster-nix/src/vm/vmar/vm_mapping.rs#L211-L213

The above path gently promotes a COW read-only page (say A) to a copied read-write page (say B) and writes new data to page B. However, no TLB caches are flushed along the path, so the application may still see the old data from page A, which will definitely cause problems.

So let's add missing TLB flushes to `VmSpace`. Actually, this is still not an elegant solution for two reasons: (i) TLB flushes are not needed if `VmSpace` is not activated at all; (ii) local TLB flushes will never work if `VmSpace` is activated on a remote CPU. I've added some comments to note these, as I think addressing them is a separate thing, and I can't figure out an easy way to address them for now.

### CODE REVIEW

**Comment by tatetian** [comment]
Flushing TLB entries properly inside the page table API makes the API easier to use, right? The main reason that we are not currently doing is because the `PageTable` may not be activated, in which case flushing TLB entries is unnecessary (maybe even dangerous?). So it seems that an instance of `PageTable` should be aware of whether it is currently activated or not. Knowing this information will also be helpful to the performance optimizations such has #811 and may be useful for correctness such case #829.

**Comment by junyang-zh** [comment]
> So it seems that an instance of PageTable should be aware of whether it is currently activated or not.

Another pro for such awareness: If the page table is only activated in this CPU, there would be no other on-going MMU page walks and we are safe to reuse recycled page tables at this point. #836 enables a mechanism using reference counts since a CPU is a referencer and the activation count is `root_frame.ref_cnt - 1`.

So it may be soon addressed.

**Comment by lrh2000** [comment]
> If the page table is only activated in this CPU, there would be no other on-going MMU page walks and we are safe to reuse recycled page tables at this point.

We may want to access or even lock page tables that is not running on any CPU, for example when implementing system calls like `ptrace` and `process_vm_readv`, moving some user memory to swap, or writing back dirty pages. So AFAIK, this statement looks a bit wired to me (assuming I understand it correctly).

**Comment by junyang-zh** [comment]
> for example when implementing system calls like ptrace and process_vm_readv, moving some user memory to swap, or writing back dirty pages

In such cases the accesses are controlled because they get locks. Recycling empty page tables in such cases are safe.

But the reason why we disabled recycling so far is that the MMU doesn't care about our locks when reading from the page tables. So there is a case that is unsafe:
 - all PTEs in a node are unmapped;
 - another CPU's MMU walked to the parent and read the PTE pointing to the node, a cache miss happened there so MMU is waiting to load the node;
 - we remove the parent's PTE that points to the unmapped node;
 - we recycle the current node, and the frame is immediately reused for other purposes;
 - the MMU of another CPU reads bad data and is may be valid! a UAF.

**Comment by lrh2000** [comment]
> But the reason why we disabled recycling so far is that the MMU doesn't care about our locks when reading from the page tables.

So it seems that we should send IPIs to all other CPUs that activate the same page table, wait for them to invalidate their TLB entries, and then return the empty page tables to the memory allocator? This is a really interesting problem that I wasn't aware of before, thanks for your explanation.

**Comment by junyang-zh** [comment]
> we should send IPIs to all other CPUs...

What I propose is when the cursor recycled the nodes we gather them to a per-page-table recycle buffer. And send all those node back to the allocator if we can ensure safety. Maybe a kernel task is needed to regularly inspect activated page tables to see if anything can be recycled. Send IPIs when suspicious usages are detected, maybe.

That seems far away. We can just have a recycle buffer for now.

**Comment by tatetian** [comment]
So... should the problem be fixed in this PR as a temporary solution or in another PR that revises the page table implementation, probably by @junyang-zh ?

**Comment by lrh2000** [comment]
> if we can ensure safety

@junyang-zh Safety aside, I'm afraid you still need to send IPIs to invalidate TLBs on other CPUs, because the application may see inconsistent data if you don't.

This is more serious if we enable PCIDs, because task switching (writing to CR3) will no longer invalidate TLBs, even if it switches page tables.

But that's off topic for this PR, maybe we can discuss it elsewhere.

> So... should the problem be fixed in this PR as a temporary solution or in another PR that revises the page table 
implementation, probably by @junyang-zh ?

@tatetian Well, I guess it's okay to accept this PR as a temporary fix? This PR literally introduces no new problems, and retains the location where previous TLB flushes were performed (note that `VmSpace::clear` flushes the TLB _before_ this PR). SMP aside (since we have no SMP support for now), I think the code in this PR works pretty well.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by tatetian** [comment]
@lrh2000 Needs to fix the conflicts

**Comment by lrh2000** [comment]
> @lrh2000 Needs to fix the conflicts

OK, now rebased and also passed the CI.

**Pull request merged**
