### PR TITLE
Bump only package version in Cargo.toml

### PR DESCRIPTION
**Pull request by StevenJiang1110**

### CODE REVIEW

**Comment by tatetian** [comment]
@StevenJiang1110 It is a good practice to add an overview to a PR so that people can know the motivation of the PR or the problem that the PR tries to solve. What is the problem that this PR attempts to solve?

**Comment by StevenJiang1110** [comment]
> @StevenJiang1110 It is a good practice to add an overview to a PR so that people can know the motivation of the PR or the problem that the PR tries to solve. What is the problem that this PR attempts to solve?

This PR is to solve [the publish osdk CI panic](https://github.com/asterinas/asterinas/actions/runs/9202311369/job/25311918928). For publishing `cargo-osdk`, we must the specify the version for each dependent crate. Since the version was commented out, I add the version back in this PR.

But the `bump_version.sh` script will update each string with pattern `version="x.x.x"` in `Cargo.toml`. Indeed, we only want to update version of the package, not the version of dependent crates.

So I change the `bump_version.sh` to only update the first occurence of `version="x.x.x"` string in `Cargo.toml`. The version of package is the first string with `version="x.x.x"` format.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by tatetian** [comment]
> > @StevenJiang1110 It is a good practice to add an overview to a PR so that people can know the motivation of the PR or the problem that the PR tries to solve. What is the problem that this PR attempts to solve?
> 
> This PR is to solve [the publish osdk CI panic](https://github.com/asterinas/asterinas/actions/runs/9202311369/job/25311918928). For publishing `cargo-osdk`, we must the specify the version for each dependent crate. Since the version was commented out, I add the version back in this PR.
> 
> But the `bump_version.sh` script will update each string with pattern `version="x.x.x"` in `Cargo.toml`. Indeed, we only want to update version of the package, not the version of dependent crates.
> 
> So I change the `bump_version.sh` to only update the first occurence of `version="x.x.x"` string in `Cargo.toml`. The version of package is the first string with `version="x.x.x"` format.

Ok. Thanks for the explanation. Next time, I expect the explanation to be included in the PR or as part of the commit messages.

**Pull request merged**
