### PR TITLE
Make atomic mode panics have clear messages

### PR DESCRIPTION
**Pull request by lrh2000**
I noticed that some CI [failed](https://github.com/asterinas/asterinas/actions/runs/12034381595/job/33550785875) due to the atomic mode break, but the error message is just totally useless.

```
[   121.337] ERROR: Uncaught panic:
	This function might break atomic mode (preempt_count = 3, is_local_irq_enabled = true)
	at /__w/asterinas/asterinas/ostd/src/task/atomic_mode.rs:41
```

We really do not need to see if the panic happens within `might_sleep`. Instead, we want to see if it happens in the subsystem that triggers the atomic mode break. For now, this is usually the line where a mutex is locked.

In Rust, if a method is annotated with [`#[track_caller]`](https://rustc-dev-guide.rust-lang.org/backend/implicit-caller-location.html), a panic in that method is reported with the line that calls the method.

So the easiest way to fix the error message is to annotate all methods in the call chain from `Mutex::lock` to `might_sleep` with `#[track_caller]`. However, for historical reasons, `might_sleep` is in a very deep position in the call chain, and cannot easily be moved to a shallower position without resolving #1483 first.

```
    Mutex::lock
 -> WaitQueue::wait_until
 -> Waiter::wait_until_or_cancelled
 -> Waker::do_wait
 -> park_current
 -> reschedule
 -> switch_to_task
```

Marking `#[track_caller]` for `might_sleep` should not be controversial. However, it may or may not be a good thing to mark all subsequent methods as `#[track_caller]`. Nevertheless, this can be treated as a workaround to allow us to have reasonable panic messages in the current CI logs. Not sure if we want to accept this, though.

### CODE REVIEW

**Review by tatetian — COMMENTED** [review]
Good job on making a good use of the `track_caller` feature!

I am a bit of nervous with the overhead of the additional, implicit argument passing added by the compiler to achieve the `track_caller` feature. Especially, when considering the fact that these are some frequently-called APIs such as mutex lock. But I guess the overheads should be minimal. So let's add it first and see if we can observe any regression in LMbench.

You may also want to add the `#[track_caller]` attribute to `UserMode::execute`, which does not invoke the scheduler, but still it may execute for an indefinite amount of time.

And by the way, I originally thought `TaskOptions::spawn`, `Task::run`, and `task::scheduler::run_new_task` should be marked `#[track_caller]`. Then, I examined the function body of `run_new_task` and found out that the latest implementation does not trigger scheduling.

https://github.com/asterinas/asterinas/blob/9608a57cb0496ec2da69de33bd40b3945afb17d6/ostd/src/task/scheduler/mod.rs#L186

But the function body still calls `might_sleep`. I think this is incorrect. Could you also fix it in this PR?

**Comment by lrh2000** [comment]
> I am a bit of nervous with the overhead of the additional, implicit argument passing added by the compiler to achieve the `track_caller` feature. Especially, when considering the fact that these are some frequently-called APIs such as mutex lock. But I guess the overheads should be minimal. So let's add it first and see if we can observe any regression in LMbench.

Although I'm also not sure if performance is affected, I _think_ that locking a mutex seems like a heavy operation anyway, while `#[track_caller]` just passes an extra pointer to let the method know who is calling it. The latter should be much lighter than locking a mutex.

> You may also want to add the `#[track_caller]` attribute to `UserMode::execute`, which does not invoke the scheduler, but still it may execute for an indefinite amount of time.

The `UserMode::execute` _does_ call the scheduler. We preempt user programs during execution, which is done with `might_preempt`.

> And by the way, I originally thought `TaskOptions::spawn`, `Task::run`, and `task::scheduler::run_new_task` should be marked `#[track_caller]`. Then, I examined the function body of `run_new_task` and found out that the latest implementation does not trigger scheduling.
> 
> https://github.com/asterinas/asterinas/blob/9608a57cb0496ec2da69de33bd40b3945afb17d6/ostd/src/task/scheduler/mod.rs#L186
>
> But the function body still calls `might_sleep`. I think this is incorrect. Could you also fix it in this PR?

I'm very confused reading this. It seems you're confusing `might_sleep` with `might_preempt`. Well, maybe the names are just literally confusing, but please note this:
 - `might_sleep` is just an assertion, asserting that we're not in atomic mode. It does nothing more than make the assertion.
 - `might_preempt` will check if the current task needs to be preempted and then _perform the preemption (if it is needed)_.

So `run_new_task` will trigger scheduling, but only if it feels that preemption is necessary. This should be the correct behavior, and I don't think there is anything to fix.

Back to this PR, marking other methods (like `Task::run`) as `#[track_caller]` may help, but it only helps a little because we have an aggressive number of wrappers on top of it (e.g. `Thread::run`/`ThreadOption::spawn`), which makes me unsure if I should mark them all as `#[track_caller]`.
 - On the one head, I don't think it's a very good idea, because if some `unwrap` fails inside, it will lead to confusing messages.
 - On the other hand, I think it's reasonable because we definitely want the atomic mode breaks to be reported on the line that calls these functions.

So, this PR originally plans to make minor changes to make the most common cases (atomic mode break due to `Mutex::lock`) have readable error messages.

In the latest changes I've added a few more places according to your comments. You can have a look to get some feelings about it.

**Comment by tatetian** [comment]
> * `might_sleep` is just an assertion, asserting that we're not in atomic mode. It does nothing more than make the assertion.
> * `might_preempt` will check if the current task needs to be preempted and then _perform the preemption (if it is needed)_.

Yes, I mixed them up. Thanks for the clarifications.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
