### PR TITLE
Fix flock lost-wakeup bugs

### LINKED ISSUE #1474: Infinite waiting in `flock` due to waiting on a `None` condition
### Describe the bug

When there is a conflict lock, the process waits to be woken up. However, the wake-up condition always returns None, meaning it is never satisfied, causing the process to wait indefinitely.

https://github.com/asterinas/asterinas/blob/2f511069eecf521661aa4d8ee3020863be75b543/kernel/src/fs/utils/flock.rs#L66-L69

A similar issue was reported in `range_lock` (#1217).

### To Reproduce

Check out [this branch](https://github.com/tangruize/asterinas/tree/test_flock) to reproduce:

flock_infinite_waiting

### PR DESCRIPTION
**Pull request by tangruize**
Fixes #1474

It is a similar fix as the one for the range lock (https://github.com/asterinas/asterinas/pull/1466#issuecomment-2431163542).

### CODE REVIEW

**Comment by grief8** [comment]
> I noticed that `flock` doesn't use the `READ` lock of `RwMutex`. we can further replace the `RwMutex` with `Mutex` for simplicity.

I think it is a reasonable proposal. Current `set_lock` does not need the check of `VecDeque<FlockItem>`.

**Review by grief8 — APPROVED** [review]
LGTM! Thanks for your contribution.

**Comment by tangruize** [comment]
> I think it is a reasonable proposal. Current set_lock does not need the check of VecDeque<FlockItem>.

I have replaced `RwMutex` with `Mutex` and tested it. pls review.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
