### PR TITLE
Rename aster-frame to ostd

### PR DESCRIPTION
**Pull request by StevenJiang1110**
This PR renames the crate `aster-frame` as `ostd`.

There are also some unsolved problems:
1. The `osdk` test in CI will fail. This is because there's no `ostd` crate in the main branch. This problem will be fixed by a following PR once this PR is merged.
2. ~It's not clear whether we should rename `aster_main` as something else. This macro is the only item that begins with `aster_` in OSTD now~. The `aster_main` has been renamed as `ostd::main`.
3. ~It's not clear whether we should re-export everything in `ostd/libs` in OSTD, for example `AlignExt` or `ktest`. Just like Rust std will re-export everything from `core` and `alloc` crate~. `ktest` is re-exported from `ostd`.

### CODE REVIEW

**Comment by tatetian** [comment]
> 2\. It's not clear whether we should rename `aster_main` as something else. This macro is the only item that begins with `aster_` in OSTD now.

I think it is logical to rename `aster_main` to `ostd_main` now that the crate implements this macro is no longer named `aster_xxx`.

**Comment by junyang-zh** [comment]
Maybe we should rethink the name "ostd"? My point is that the name "ostd" undermined the concept of the frame kernel architecture, where "ostd" encapsulates the unsafe code. STD seemed not necessary to be minimal.

"ostd" as "os-std" also seems a bad pun. "aster-std" even seemed clearer.

I would liked to suggest "aster-core". For there is also a core crate in Rust std. "core" sounds a bit more encapsulated. We could provide another "aster-std" (or "ostd" if you wish).

**Comment by tatetian** [comment]
One goal of the Asterinas community is to foster a more vibrant Rust OS ecosystem. Such an ecosystem demands better tooling (i.e., OSDK) and infrastructure crate (i.e., `ostd`). This tool and crate should be as neutral as possible and decoupled from Asterinas. As such, their names should not include "aster".

The word "std" does not imply minimality or framework. So it does not reflect the properties of the framekernel architecture. This is probably the downside of choosing the name "ostd". But think about the benefit: the name conveys to the audience its ambition of becoming the unofficial standard crate for OS kernel development. I think the benefit outweighs the downside.

**Comment by lrh2000** [comment]
>  rename aster_main to ostd_main

Some alternatives (note the consistency with `#[ktest]` and `#[aster_init]` in https://github.com/asterinas/asterinas/issues/935):
 - `#[ostd_main]`, `#[ostd_init]`, and `#[ostd_test]`
 - `#[kmain]`, `#[kinit]`, and `#[ktest]`
 - `#[ostd::main]`, `#[ostd::init]`, and `#[ostd::test]`

**Comment by StevenJiang1110** [comment]
> Some alternatives (note the consistency with `#[ktest]` and `#[aster_init]` in #935):
> 
> * `#[ostd_main]`, `#[ostd_init]`, and `#[ostd_test]`
> * `#[kmain]`, `#[kinit]`, and `#[ktest]`
> * `#[ostd::main]`, `#[ostd::init]`, and `#[ostd::test]`

Thanks for your advice!

Personally, I prefer the last pattern. In this pattern, these macros can be named simply as `main`, `init`, and `test`, and they would be re-exported from the `ostd` crate. Even if the name of the `ostd` crate changes over time, the macros crate itself does not need to be modified.

Another evidence is that tokio follows the same naming rule. For example, users can use [`tokio::main`](https://docs.rs/tokio-macros/2.3.0/src/tokio_macros/lib.rs.html#206) and [`tokio::test`](https://docs.rs/tokio-macros/2.3.0/src/tokio_macros/lib.rs.html#427) to mark their functions.

**Comment by lrh2000** [comment]
Actually, I was wondering if we should keep `#[cfg(ktest)]` as is, or use `#[cfg(test)]` instead.

I don't really mind keeping it as is, if using `#[cfg(test)]` ever causes conflicts or other misunderstandings.

But one advantage of using `cfg(test)` is that it will be better integrated with the LSP (i.e., `rust-analyzer`) and perhaps other IDEs, because they will enable `cfg(test)` by default, making the process of writing tests more flexible.

**Comment by tatetian** [comment]
> Actually, I was wondering if we should keep `#[cfg(ktest)]` as is, or use `#[cfg(test)]` instead.
> 
> I don't really mind keeping it as is, if using `#[cfg(test)]` ever causes conflicts or other misunderstandings.

These are some valid options. But none of them is a clear winner. So I would rather err on the safest option, which is to value clarity above all else. `#[cfg(ostd::test)]` is the most explicit and clear one. We can always switch to another option in the future as we collect more user feedbacks.

> But one advantage of using `cfg(test)` is that it will be better integrated with the LSP (i.e., `rust-analyzer`) and perhaps other IDEs, because they will enable `cfg(test)` by default, making the process of writing tests more flexible.

Surely, there are some ways to configure the LSP to enable `#[cfg(ostd::test)]` by default.

**Comment by StevenJiang1110** [comment]
> These are all valid options. But none of them is a clear winner. So I would rather err on the safest option, which is to value clarity above all else. `#[cfg(ostd::test)]` is the most explicit and clear one. And only four letters longer than the standard notation. We can always switch to another option in the future as we collect more user feedbacks.

After conducting a simple test, it has been determined that `#[cfg(ostd::test)]` is not a valid configuration in Rust. The Rust compiler requires the configuration name to be a valid identifier, and the path separator `::` is not allowed to be used as a configuration name.

There are alternative styles that can be used. For instance, `#[cfg(ostd_test)]` or `#[cfg(ostd = "test")]`. However, it is uncertain which style is better.

**Comment by tatetian** [comment]
> > These are all valid options. But none of them is a clear winner. So I would rather err on the safest option, which is to value clarity above all else. `#[cfg(ostd::test)]` is the most explicit and clear one. And only four letters longer than the standard notation. We can always switch to another option in the future as we collect more user feedbacks.
> 
> After conducting a simple test, it has been determined that `#[cfg(ostd::test)]` is not a valid configuration in Rust. The Rust compiler requires the configuration name to be a valid identifier, and the path separator `::` is not allowed to be used as a configuration name.
> 
> There are alternative styles that can be used. For instance, `#[cfg(ostd_test)]` or `#[cfg(ostd = "test")]`. However, it is uncertain which style is better.

Is it possible to write in the following way?

```rust
use ostd::prelude::*;

#[cfg(ktest)]
mod {
    #[ktest]
    fn test_foo() {}
}
```

**Comment by StevenJiang1110** [comment]
> Is it possible to write in the following way?
> 
> ```rust
> use ostd::prelude::*;
> 
> #[cfg(ktest)]
> mod {
>     #[ktest]
>     fn test_foo() {}
> }
> ```
> 
> Using `ktest` directly is probably better because (1) it is short, (2) it won't cause any ambiguity, and (3) it emphasizes the fact that these tests, unlike their Rust std counterparts, run in the kernel mode.

Sure, this can be done in this PR.

**Comment by tatetian** [comment]
> > Is it possible to write in the following way?
> > ```rust
> > use ostd::prelude::*;
> > 
> > #[cfg(ktest)]
> > mod {
> >     #[ktest]
> >     fn test_foo() {}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Using `ktest` directly is probably better because (1) it is short, (2) it won't cause any ambiguity, and (3) it emphasizes the fact that these tests, unlike their Rust std counterparts, run in the kernel mode.
> 
> Sure, this can be done in this PR.

@junyang-zh and @lrh2000 What do you think? Let's keep `ktest`?

**Comment by lrh2000** [comment]
> @junyang-zh and @lrh2000 What do you think? Let's keep ktest?

I think that keeping `ktest` is fine. I don't have a strong preference here.

My personal preference is to maintain consistency. To me, using `kmain`, `kinit`, and `ktest` seems quite reasonable.

**Comment by tatetian** [comment]
> > @junyang-zh and @lrh2000 What do you think? Let's keep ktest?
> 
> I think that keeping `ktest` is fine. I don't have a strong preference here.
> 
> My personal preference is to maintain consistency. To me, using `kmain`, `kinit`, and `ktest` seems quite reasonable.

Maintaining consistency is a concern. But the `k` prefix of `kmain` is kind of redundant with the crate name `ostd` (`os` already means `k`). If we are going to do this in the name of consistency, does it mean that all future macros or attributes of `ostd` should start with `k`? This does not sound right to me.

On the other hand, should we remove `k` prefix from `ktest` for consistency? I don't think so. Because that would be too error prone.

```rust
// If the developer forgets to write the following import, then the test module below would still compile
// with `cargo osdk test`. But to the developer's surprise, no tests would get running.
// It is much easier to spot the problem if ostd's test cfg and attribute are named ktest.
// use ostd::prelude::*;

#[cfg(test)]
mod my_test {
    #[test]
    fn test() { ... }
}
```

For these reasons, I am in favor of the combination of `ktest`, `ostd::main`, and `ostd::init`.

**Comment by lrh2000** [comment]
> Maintaining consistency is a concern. But the `k` prefix of `kmain` is kind of redundant with the crate name `ostd` (`os` already means `k`). If we are going to do this in the name of consistency, does it mean that all future macros or attributes of `ostd` should start with `k`? This does not sound right to me.
> 
> On the other hand, should we remove `k` prefix from `ktest` for consistency? I don't think so. Because that would be too error prone.
> 
> ```rust
> // If the developer forgets to write the following import, then the test module below would still compile
> // with `cargo osdk test`. But to the developer's surprise, no tests would get running.
> // It is much easier to spot the problem if ostd's test cfg and attribute are named ktest.
> // use ostd::prelude::*;
> 
> #[cfg(test)]
> mod my_test {
>     #[test]
>     fn test() { ... }
> }
> ```
> 
> For these reasons, I am in favor of the combination of `ktest`, `ostd::main`, and `ostd::init`.

OK, I thought you were suggesting that both `main` and `init` are included in `ostd::prelude` before, so it might make sense to add the `k` prefix to all of them. This turns out to be a misunderstanding.

If `main` and `init` do not live in preclude, it makes sense not to have the `k` prefix on them. I agree. (After all, even if we add the `k` prefix, `ostd::kmain` is not consistent with `ktest`, so adding the prefix makes little sense).

Well, the main inconsistency comes from the fact that the `ktest` macro lives in `preclude`, but the `main` macro does not. This inconsistency is, however, for consistency between the configuration name and the attribute macro. So we can write `#[cfg(ktest)]` and `#[ktest]`.

The solution that I want to compare to is just not to modify the configuration name, but rename the attribute macro:
```rust
#[cfg(ktest)]
mod my_test {
    #[ostd::test]
    fn test() { ... }
}
```
It _might_ be better, in the sense that
 1. we have consistency between `ostd::main` and `ostd::test`, and
 2. _if_ we can change `#[cfg(ktest)]` to `#[cfg(test)]`, either now or in the future, we will also have consistency between `cfg(test)` and `ostd::test` (I explained why it _might_ be better to adopt the change in https://github.com/asterinas/asterinas/pull/951#issuecomment-2182369196).

But I don't think it's clearly better for now, especially if we decide to use `cfg(ktest)` instead of `cfg(test)`, as the inconsistency between `cfg(ktest)` and `ostd::test` also look a bit wired.

While I still want to offer this solution as a reference and list its pros and cons, I have no preference between this solution and yours, as neither is definitely better than the other.

**Comment by lrh2000** [comment]
In summary, my general feeling is that whether `#[ktest]` or `#[ostd::test]` is better depends on whether we choose `cfg(ktest)` or `cfg(test)`. So this may be a separate issue that we can discuss in the future, rather than in this PR. For now, I can accept either the solution in https://github.com/asterinas/asterinas/pull/951#issuecomment-2186346183 or the solution in https://github.com/asterinas/asterinas/pull/951#issuecomment-2187927577.

**Comment by junyang-zh** [comment]
Well I'd like to add some story for the name `ktest`: we actually planned to perform unit tests on the host OS user space natively, without running QEMU (#73). By the time `ktest` was introduced, we think maybe we can also do it, so leaving `test` for future usages.

It turns out that we currently don't need the user mode test for kernel-specific crates, so the name `test` is unused.

Indeed, `test` is a well known cfg for development tools. And we currently even don't enable the `ktest` cfg for lints. You get warning for unit tests right now.

I don't have a preference for `ktest` or `test` for now. Just to add some noise in the discussion.

**Comment by lrh2000** [comment]
> user mode test

This may be a bit off-topic for this PR, but I don't think we ever need `cfg(ktest)` for this reason. I would prefer to add a new configuration name for running user-mode code and/or doing user-mode tests.

```rust
#[cfg(not(test))]
const BUFFER_SIZE: usize = 1024 * 1024;
#[cfg(test)]
const BUFFER_SIZE: usize = 16; // Use smaller buffers in unit tests.

#[cfg(not(umode))]
impl Xxx { /* Implementations running in the kernel mode */}

#[cfg(umode)]
impl Xxx { /* Implementations running in the user mode */ }

#[cfg(test)]
mod test {
    // This test can be run in either user or kernel mode.
    #[ostd::test]
    fn test_xxx() {}
}
```

Of course, we have a long list of unresolved questions about how to do user-mode testing (and maybe even whether we need it). But I think the general idea that maybe we don't need `cfg(ktest)` because of this remains.

**Comment by StevenJiang1110** [comment]
Short summary for `ktest` in this PR: The current PR uses the following form for the `ktest` macro by simply re-export `ktest` macro from the `ostd` crate.

```rust
#[cfg(ktest)]
mod test {
    use ostd::prelude::*;
    
    #[ktest]
    fn test() {}
}
```

While another possible style is

```rust
#[cfg(test)]
mod test {
    #[ostd::test]
    fn test() {}
}
```
Whether we should switch to the second form may be discussed in a seperate issue.

**Comment by StevenJiang1110** [comment]
> Indeed, test is a well known cfg for development tools. And we currently even don't enable the ktest cfg for lints. You get warning for unit tests right now.

Yeah, this is a separate annoying problem. It's not just the lint error for the unknown cfg (i.e., `ktest`) that started being checked by the new toolchain, but also other lint errors like defining unused variables. Unfortunately, the lint check currently does not cover the code under `cfg(ktest)`.

**Comment by StevenJiang1110** [comment]
The OSDK CI failure should be fixed by a following bump version PR, since OSDK relies on the latest main branch.

**Comment by tatetian** [comment]
Just to clarity. So this form does not suffer from the annoying lint and IDE warnings?

```rust
#[cfg(test)]
mod test {
    #[ostd::test]
    fn test() {}
}
```

If the warning/errors are so annoying, I would vote for this option.

**Comment by lrh2000** [comment]
> Just to clarity. So this form does not suffer from the annoying lint and IDE warnings?

I'm not familiar with the internal details, but my experience is that:
 - `cargo check --all-targets`/`cargo check --test` will cover `cfg(test)`. I have just quickly scanned the help message given by `cargo check --help`, but don't see any way to get it to cover `cfg(ktest)` at the moment.
 - The `rust-analyzer` LSP automatically enables `cfg(test)`, making the process of writing tests much more flexible, just like writing normal code. I think there may be a way to make it work with `cfg(ktest)`, but I _do_ think it is better to make it work out of the box.

**Comment by StevenJiang1110** [comment]
> * `cargo check --all-targets`/`cargo check --tests` will cover `cfg(test)`. I have just quickly scanned the help message given by `cargo check --help`, but don't see any way to get it to cover `cfg(ktest)` at the moment.

`RUSTFLAGS="--cfg ktest" cargo check` will check the code under `[cfg(ktest)]`. This is what OSDK done when running ktest now.

**Comment by StevenJiang1110** [comment]
After trying, it seems that `--cfg test` cannot be used. The error message is like follows:

```text
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-none` target may not support the standard library
  = note: `std` is required by `core` because it does not declare `#![no_std]`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`
```

If building with `--cfg test`, the `core` crate will depends on `std`. But we cannot link with `std`. So we maynot use `#[cfg(test)]` for test cases.

**Comment by lrh2000** [comment]
> If building with --cfg test, the core crate will depends on std.

Thank you for your testing. However, I believe this is a false positive and reveals a potential bug in the OSDK.

If you specify `RUSTFLAGS="--cfg test"`, Cargo will pass the argument to the current crate and _all its dependencies_. So Cargo will not only recompile the current crate but also _all its dependencies_ because of the compiler flag change, which is not correct and not efficient.

If you try `cargo build` and `cargo test` on a normal crate, you will notice that it _only_ recompiles the current crate without recompiling the dependencies, which makes sense to me since we never intend to run tests in the dependencies.

The `--cfg test` (or `--cfg ktest`) should only be specified for the current crate, which should be done using [`cargo rustc`](https://doc.rust-lang.org/cargo/commands/cargo-rustc.html) instead of modifying the RUSTFLAGS environment variable. We don't want to enable any new configuration on the core crate, neither `test` nor `ktest` (although enabling the latter will literally do nothing since the `core` crate never uses `cfg(ktest)`).

**Comment by StevenJiang1110** [comment]
> The --cfg test (or --cfg ktest) should only be specified for the current crate, which should be done using [cargo rustc](https://doc.rust-lang.org/cargo/commands/cargo-rustc.html) instead of modifying the RUSTFLAGS environment variable. We don't want to enable any new configuration on the core crate, neither test nor ktest (although enabling the latter will literally do nothing since the core crate never uses cfg(ktest)).

I think you are right. It would be beneficial to refactor OSDK  to support a behavior similar to `cargo test`. I have created a separate issue #974 specifically for this purpose. However, it presents a bit challenge for OSDK because the current crate for `cargo osdk test` is not the crate for test, but the `target/base` crate.

Regarding the current pull request, it will maintain the usage of `#[cfg(ktest)]`. Once issue #974 is resolved, we can consider switching to `#[cfg(test)]` in following PRs.

**Comment by tatetian** [comment]
In conclusion, let's keep the current syntax.

```rust
#[cfg(ktest)]
mod test {
    use ostd::prelude::*;
    
    #[ktest]
    fn test() {}
}
```

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
