### PR TITLE
Fix lost wakeup in `range_lock` caused by waiting on an outdated `waitqueue`

### LINKED ISSUE #1464: Lost wakeup in `range_lock` after replacing overlapping locks
### Describe the bug

When a process re-acquires a range lock to change its type from `WRITE` to `READ`, the original lock is replaced along with its `waitqueue`. If another process is waiting for the lock due to a conflict, it is woken up when the original lock is removed. However, the new lock still causes a conflict, so the waiting process attempts to re-enqueue on the old `waitqueue`, which no longer exists. This results in lost-wakeup, leaving the process waiting indefinitely.

https://github.com/asterinas/asterinas/blob/1fe0a138f97bc5dc59deb23e7c55fa628035996a/kernel/src/fs/utils/range_lock/mod.rs#L335-L338

### To Reproduce

1. P1 acquires a `WRITE` lock on range `[0, 1)`
2. P2 attempts to acquire a `WRITE` lock on the same range but waits due to a conflict
3. P1 acquires a READ lock on file range [0, 1), which replaces the old lock
4. P1 releases the range lock
5. P2 should acquire the WRITE lock but waits indefinitely

Comparison of the behavior in Asterinas (top) vs. Linux (bottom):

1. Checkout [this branch](https://github.com/tangruize/asterinas/tree/test_range_lock)
2. Run docker
3. Build test case `cd test/apps/range_lock && make`
4. Run Asterinas: `make run`
5. Run testcase in Asterinas: `cd test/range_lock && ./range_lock`

asterinas_acquire_lock_timeout

### PR DESCRIPTION
**Pull request by tangruize**
Fixes #1464

This fix fixes both the first lost wakeup scenario (`scenario1`) and the [second scenario](https://github.com/asterinas/asterinas/issues/1464#issuecomment-2418701509) (`scenario2`).

`scenario2` can be reproduced on [this branch](https://github.com/tangruize/asterinas/tree/test_range_lock2):
scenario2_reproduce

### Behavior After the Fix

`scenario1`:

fixed_scenario1

`scenario2`:

fixed_scenario2

### CODE REVIEW

**Comment by tangruize** [comment]
I noticed that `flock.rs` doesn't wait on a condition and always renews `conflict_lock`. I think this approach is also valid:

https://github.com/asterinas/asterinas/blob/2f511069eecf521661aa4d8ee3020863be75b543/kernel/src/fs/utils/flock.rs#L66-L69
https://github.com/asterinas/asterinas/blob/2f511069eecf521661aa4d8ee3020863be75b543/kernel/src/fs/utils/flock.rs#L146

**Comment by grief8** [comment]
> I noticed that `flock.rs` doesn't wait on a condition and always renews `conflict_lock`. I think this approach is also valid:
> 
> https://github.com/asterinas/asterinas/blob/2f511069eecf521661aa4d8ee3020863be75b543/kernel/src/fs/utils/flock.rs#L66-L69
> 
> 
> https://github.com/asterinas/asterinas/blob/2f511069eecf521661aa4d8ee3020863be75b543/kernel/src/fs/utils/flock.rs#L146

This brings a potential problem from #1217, so I think the current modification is ok.

**Comment by tangruize** [comment]
> This brings a potential problem from https://github.com/asterinas/asterinas/pull/1217, so I think the current modification is ok.

You're right. I verified the "fix" by waiting on a `None` condition, which violates the starvation-free property. The issue arises from dropping `conflict_lock`, which wakes up all waiting processes. If two processes wake each other in an interleaving pattern, it leads to high CPU usage until the lock is released.

Moreover, when many processes are waiting on `conflict_lock`, they can acquire the `WRITE` lock, while the lock holder might not, resulting in a livelock.

I suspect this problem might also exist in flock. I’ll verify it.

**Comment by tangruize** [comment]
Unfortunately, this fix isn't correct, and relying on the reference count is also fragile. For example, if two processes are waiting on the conflict lock, the reference count remains at two after the lock is removed from the list. I'll work on finding a correct fix.

**Comment by tangruize** [comment]
Even if we directly check whether the conflict still exists in the list and break the wait if it doesn't, this approach is still incorrect. The reason is that `conflict_lock.wait_until()` is not protected by a WRITE lock on the list. This means the `conflict_lock` could be removed from the list before `conflict_lock.wait_until()` is called, resulting in no wakeup for the `conflict_lock`. This bug also exists in flock.

**Comment by grief8** [comment]
I think `condvar` can potentially be used for more efficient waiting and notification, i.e., integrate `Condvar` into `set_lock` to improve synchronization instead of `waitqueue`. See [`example`](https://github.com/asterinas/asterinas/blob/b7d101b98c52c73a83a6266c2fc3d7c48921915a/kernel/src/process/sync/condvar.rs#L254-L362).

**Comment by tangruize** [comment]
Enqueuing a waker within the WRITE lock protection and continuing the loop after wakeup fixes above issues. It avoids cloning `conflict_lock`, avoiding unnecessary wakeups (when the clone is dropped).
Tests for three bug scenarios are in [this branch](https://github.com/tangruize/asterinas/tree/test_range_lock). To check the fix behavior, rebase `fix_range_lock` branch.

**Comment by tangruize** [comment]
There are some clones when iterating the list, which could trigger unnecessary wakeups when dropped. While they don't cause bugs, switching to references can reduce these operations and slightly improve performance. 

https://github.com/asterinas/asterinas/blob/4658b62f90ec326fa4a0054f3a44e8ab70b1e7f7/kernel/src/fs/utils/range_lock/mod.rs#L283-L284

If needed, I can open another PR to address this and verify the improvements.

**Review by grief8 — APPROVED** [review]
LGTM! Thank you for the optimization.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by lrh2000** [comment]
@tangruize  Thanks for the detailed explanation! I have checked the code and related discussion accordingly, and it seems to be a legal use case. If that's the case, I don't mind just removing the `#[doc(hidden)]` markers as long as we find enough motivating examples that use the hidden API legally.

That said, I think we actually still want to use `wait_until`/`pause_until` in this case, but write the code like this:
```rust
	let (waiter, waker) = Waiter::new_pair();
	waiter.pause_until(|| {
		// Lock, check conflict locks, and enqueue the waker
		// return `Some(_)` if no locks are conflict
	})
```

 - I believe that signals can interrupt the waiting process, so `pause` is more desirable than `wait`. Let's focus on `pause` below.
 - `pause_until` ensures that wakeup events won't be lost even if signals and wakeup events come at the same time. (Ideally, `wait_until` is preferable to `wait` for the same reason, but `wait_until` is simpler because it does not need to consider signals).
 - I notice the reason why we still need to manually enqueue the waker is that the wait queue is behind some locks, so we cannot call `WaitQueue::pause_until` directly, instead we have to do `Waiter::pause_until` and enqueue the waker manually.
   - I found that this argument is valid for exposing `enqueue` as a public API. Otherwise you can just write a `Vec<Waker>` to store the enqueued wakers and call `wake_up` manually, this isn't necessary as we want to reuse the `WaitQueue` code.

> I'm concerned that iterating over the list to check for the `conflict_lock` multiple times might be a bit slower than the current fix.

`Waiter::wait_until`/`Waiter::pause_until` should not have any "fast paths" that lead to unnecessary double checking. The upper level users (like `WaitQueue`) can add the fast paths if they feel it is necessary.

However, to use `Waiter::pause_until`, it is necessary to create a `Waiter` in advance. Hopefully the overhead will be acceptable.

By the way, with this PR we don't need `Arc<WaitQueue>` anymore. We can directly use `WaitQeueue` instead, which can save some unnecessary heap allocations.

**Pull request merged**
