### PR TITLE
Bring OSDK's full support of QCOW2 booting

### PR DESCRIPTION
**Pull request by junyang-zh**
`grub-qcow2` will fail. I don't know why.

```
BdsDxe: failed to load Boot0001 "UEFI QEMU DVD-ROM QM00005 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x2,0xFFFF,0x0): Not Found
```

### CODE REVIEW

**Comment by tatetian** [comment]
> `grub-qcow2` will fail. I don't know why.

I don't why what you are saying I don't know why. Is the implementation in this PR correct or not? 👀

**Comment by junyang-zh** [comment]
`make run BOOT_METHOD=grub-qcow2` still fail in regular environment no matter what interface used. This may work for TD. Need further investigation.

**Comment by Hsy-Intel** [comment]
Tested in TDX configuration, works fine.

**Comment by Hsy-Intel** [comment]
> > Tested in TDX configuration, works fine.
> 
> Insane. There must be some nuance in either TDVF/OVMF, TDX-QEMU or TDX-GRUB.

Yes. There are many patches for TDX. https://github.com/intel/tdx-tools/tree/tdx-1.5/build/ubuntu-22.04

**Comment by tatetian** [comment]
Since it has been confirmed that the PR can work TDX, I am merging this PR despite of its known issue for normal VMs.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
