### PR TITLE
Fix panic when transfer `how` to enum in sys_rt_sigprocmask()

### LINKED ISSUE #1173: Reachable unwrap in sys_rt_sigprocmask()
### Describe the bug
There is a reachable unwrap in `sys_rt_sigprocmask()` at kernel/aster-nix/src/syscall/rt_sigprocmask.rs:21 when make a `rt_sigprocmask ` syscall with specific arguments.

https://github.com/asterinas/asterinas/blob/4844e7ca7ca6d78896a51a71487a6fdfe9ca6654/kernel/aster-nix/src/syscall/rt_sigprocmask.rs#L14-L21

### To Reproduce
1. Compile a program which calls `mmap` with specific arguments:
```C
#include <stdio.h>
#include <sys/syscall.h>
#include <unistd.h>
#include <signal.h>
#include <string.h>
#include <errno.h>

int main() {
    int how = 0xfffc;
    sigset_t set;
    sigset_t oset;
    size_t sigsetsize = 128;

    memset(&set, 0, sizeof(set));
    memset(&oset, 0, sizeof(oset));
    sigaddset(&set, 3);

    long result = syscall(SYS_rt_sigprocmask, how, &set, &oset, sigsetsize);

    return 0;
}
```
2. Run the compiled program in Asterinas.

### Expected behavior

Asterinas reports panic and is terminated.

### Environment

- Official docker asterinas/asterinas:0.6.2
- 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
- Asterinas version: main 4844e7c

### Logs
```
~ # /root/rt_sigprocmask-test 
panicked at /root/asterinas/kernel/aster-nix/src/syscall/rt_sigprocmask.rs:21:41:
called `Result::unwrap()` on an `Err` value: InvalidValue
Printing stack trace:
   1: fn 0xffffffff88838040 - pc 0xffffffff88838058 / registers:

     rax               0x12; rdx 0xffffffff889ede68; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f72a540;

   2: fn 0xffffffff88837e20 - pc 0xffffffff88837f98 / registers:

     rax               0x12; rdx 0xffffffff889ede68; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f72a550;

   3: fn 0xffffffff88049000 - pc 0xffffffff8804900a / registers:

     rax               0x12; rdx 0xffffffff889ede68; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f72a6d0;

   4: fn 0xffffffff8895cec0 - pc 0xffffffff8895cf42 / registers:

     rax               0x12; rdx 0xffffffff889ede68; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f72a6e0;

   5: fn 0xffffffff8893a1f0 - pc 0xffffffff8893a31b / registers:

     rax               0x12; rdx 0xffffffff889ede68; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f72a770;

   6: fn 0xffffffff883c4690 - pc 0xffffffff883c471b / registers:

     rax               0x12; rdx 0xffffffff889ede68; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f72a870;

   7: fn 0xffffffff8840ade0 - pc 0xffffffff88411190 / registers:

     rax               0x12; rdx 0xffffffff889ede68; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f72ab40;

   8: fn 0xffffffff8840ab00 - pc 0xffffffff8840ab8e / registers:

     rax               0x12; rdx 0xffffffff889ede68; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f7403d0;

   9: fn 0xffffffff88524040 - pc 0xffffffff88524bbf / registers:

     rax               0x12; rdx 0xffffffff889ede68; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f740570;

  10: fn 0xffffffff882259d0 - pc 0xffffffff882259de / registers:

     rax               0x12; rdx 0xffffffff889ede68; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f740f90;

  11: fn 0xffffffff8882cbf0 - pc 0xffffffff8882cc06 / registers:

     rax               0x12; rdx 0xffffffff889ede68; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f740fb0;

  12: fn 0xffffffff88798b20 - pc 0xffffffff88798b89 / registers:

     rax               0x12; rdx 0xffffffff889ede68; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f740fd0;

  13: fn                0x0 - pc                0x0 / registers:

     rax               0x12; rdx 0xffffffff889ede68; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f741000;

[OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) /root/asterinas/ostd/src/panicking.rs:107
(  2) /root/asterinas/ostd/src/panicking.rs:59
(  3) au2ndt6r5ksv2yyhocg58xyv7:?
(  4) ??:?
(  5) ??:?
(  6) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1102
(  7) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:173
(  8) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:323
(  9) /root/asterinas/kernel/aster-nix/src/thread/task.rs:69
( 10) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79
( 11) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2077
( 12) /root/asterinas/ostd/src/task/task.rs:295
make: *** [Makefile:153: run] Error 1
```

### PR DESCRIPTION
**Pull request by Marsman1996**
Fix #1173

### CODE REVIEW

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by Marsman1996** [comment]
Well, with this fix, another reachable unwrap could be triggered.

https://github.com/asterinas/asterinas/blob/40c2acf29d0596f77cfaf722b4c414a256605ac3/kernel/aster-nix/src/syscall/rt_sigprocmask.rs#L29C13-L29C14

Reproducer syscall program:
```C
#include <stdio.h>
#include <sys/syscall.h>
#include <unistd.h>
#include <signal.h>
#include <string.h>
#include <errno.h>

int main() {
    syscall(SYS_rt_sigprocmask, 0x0, 0x8, 0x9, 128);

    return 0;
}

```

The log:
```
~ # /root/rt_sigprocmask-test.c 
[    11.991] ERROR: sigset size is not equal to 8
panicked at /root/asterinas/kernel/aster-nix/src/syscall/rt_sigprocmask.rs:29:58:
called `Result::unwrap()` on an `Err` value: Error { errno: EFAULT, msg: Some("Bad user space pointer specified") }
Printing stack trace:
   1: fn 0xffffffff887f28b0 - pc 0xffffffff887f28c8 / registers:

     rax               0x12; rdx 0xffffffff889eb878; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6aa560;

   2: fn 0xffffffff887f2690 - pc 0xffffffff887f2808 / registers:

     rax               0x12; rdx 0xffffffff889eb878; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6aa570;

   3: fn 0xffffffff88049000 - pc 0xffffffff8804900a / registers:

     rax               0x12; rdx 0xffffffff889eb878; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6aa6f0;

   4: fn 0xffffffff88962070 - pc 0xffffffff889620f2 / registers:

     rax               0x12; rdx 0xffffffff889eb878; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6aa700;

   5: fn 0xffffffff8893f3a0 - pc 0xffffffff8893f4cb / registers:

     rax               0x12; rdx 0xffffffff889eb878; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6aa790;

   6: fn 0xffffffff88577f40 - pc 0xffffffff8857830d / registers:

     rax               0x12; rdx 0xffffffff889eb878; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6aa890;

   7: fn 0xffffffff884b43c0 - pc 0xffffffff884ba770 / registers:

     rax               0x12; rdx 0xffffffff889eb878; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6aab40;

   8: fn 0xffffffff883f30c0 - pc 0xffffffff883f314e / registers:

     rax               0x12; rdx 0xffffffff889eb878; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c03d0;

   9: fn 0xffffffff884290e0 - pc 0xffffffff88429c5f / registers:

     rax               0x12; rdx 0xffffffff889eb878; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c0570;

  10: fn 0xffffffff8806b390 - pc 0xffffffff8806b39e / registers:

     rax               0x12; rdx 0xffffffff889eb878; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c0f90;

  11: fn 0xffffffff88843ea0 - pc 0xffffffff88843eb6 / registers:

     rax               0x12; rdx 0xffffffff889eb878; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c0fb0;

  12: fn 0xffffffff88826560 - pc 0xffffffff888265c9 / registers:

     rax               0x12; rdx 0xffffffff889eb878; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c0fd0;

  13: fn                0x0 - pc                0x0 / registers:

     rax               0x12; rdx 0xffffffff889eb878; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c1000;

[OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) /root/asterinas/ostd/src/panicking.rs:107
(  2) /root/asterinas/ostd/src/panicking.rs:59
(  3) 2lm2gcl5stoetk1c1j2exy2o7:?
(  4) ??:?
(  5) ??:?
(  6) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1102
(  7) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:173
(  8) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:323
(  9) /root/asterinas/kernel/aster-nix/src/thread/task.rs:69
( 10) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79
( 11) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2077
( 12) /root/asterinas/ostd/src/task/task/mod.rs:310
```

**Comment by Marsman1996** [comment]
Shall I just `?` it?

**Comment by tatetian** [comment]
> Shall I just `?` it?

This should be ok. An error on type conversion usually results in `EINVAL`, which is correct in this case.

We are currently sloppy about error numbers. There are too many error codes for too many possible error situations of too many system calls. Getting them all right is not our priority at this stage of development. The bottom line is making the gvisor test suites happy.

**Pull request merged**
