### PR TITLE
Work around a QEMU bug in virtio console pasting

### PR DESCRIPTION
**Pull request by lrh2000**
Quoted from https://lore.kernel.org/qemu-devel/20240707111940.232549-3-lrh2000@pku.edu.cn/T/#u:

```
This commit fixes a bug that causes incorrect results when pasting more
than 32 bytes, the size of the receive buffer b->buffer, into the virtio
console.

Example (note that the last 32 bytes are always correct, but something
goes wrong just before the last 32 bytes):

	Pasting  abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()
	Received abcdefg)EFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()EFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()

The root cause of this bug is as follows:

[..]
```

The example shown in the commit above is exactly what happens in Asterinas, so I won't repeat the description.

We can work around the QEMU bug in Asterinas by setting the length of the virtio receive buffer to one, so that the buggy QEMU function [mux_chr_can_read](https://github.com/qemu/qemu/blob/f2cb4026fccfe073f84a4b440e41d3ed0c3134f6/chardev/char-mux.c#L203) will return either zero or one. Previously, the function might return the size of the receive buffer, which is wrong because [mux_can_read](https://github.com/qemu/qemu/blob/f2cb4026fccfe073f84a4b440e41d3ed0c3134f6/chardev/char-mux.c#L220) cannot handle that many bytes correctly. See the description of QEMU's fix patch for details.

The bug was originally discovered by @skpupil.

### CODE REVIEW

**Comment by tatetian** [comment]
@sdww0 Could you review this PR? Thanks.

**Review by sdww0 — APPROVED** [review]
LGTM.

**Comment by lrh2000** [comment]
Writing the comments twice might not be good, so I create a new function to abstract the common operations and also avoid duplicating the comments. No change in semantics though.

**Comment by tatetian** [comment]
> Writing the comments twice might not be good, so I create a new function to abstract the common operations and also avoid duplicating the comments. No change in semantics though.

That's the spirit 👍

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
