### PR TITLE
Optimize the latency of lmbench-signal-prot

### PR DESCRIPTION
**Pull request by StevenJiang1110**
This PR optimizes the lmbench-signal-prot benchmark, reducing the latency from 0.58us to 0.47us.

This benchmark is used to test the fault signal path when unrecoverable page fault occurs. The main job in this PR is to 
1. optimize some redundant lock
2. introduce fast path for enqueue signal: If the signal is sent to current thread or is a fault signal, we can skip permission check and directly enqueue the sigqueue to the current thread.

### CODE REVIEW

**Comment by tatetian** [comment]
@StevenJiang1110 Need to fix the failed tests (if they are related to this PR)

**Comment by StevenJiang1110** [comment]
@boterinas rerun

**Comment by StevenJiang1110** [comment]
> @StevenJiang1110 Need to fix the failed tests (if they are related to this PR)

This problem seems to be not related with this PR. The failure in CI is in random place and my local run cannot reproduce the same problem.

**Comment by StevenJiang1110** [comment]
@boterinas rerun

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
